### ISSUE TITLE
VPA memory metric unit should match kubernetes defaults (K vs k) 

### ISSUE THREAD

**Issue by eatwithforks** [kubernetes/autoscaler#3430] opened 2020-08-13 20:39 UTC
In the recommendations, for memory:                                

Actual:
```
"memory": "131072k"  
```

Expected:
```
"memory": "131072K"  
```
So unit parsing logic can be re-used.

Kubernetes defaults: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#meaning-of-memory
```
Limits and requests for memory are measured in bytes. You can express memory as a plain integer or as a fixed-point integer using one of these suffixes: E, P, T, G, M, K. You can also use the power-of-two equivalents: Ei, Pi, Ti, Gi, Mi, Ki. For example, the following represent roughly the same value:
```

**Comment by bskiba** [comment] 2020-08-20 16:18
There is definitely room for improvement in VPA presentation here. Looking for people interested in fixing this.

**Comment by bskiba** [comment] 2020-08-20 16:26
This is actually duplicate of #3323, so I'll close this one if that's ok

**Closed by bskiba** 2020-08-20 16:26 UTC
Labels: good first issue, help wanted, vertical-pod-autoscaler
