### ISSUE TITLE
Vertical Pod Autoscaler: load cpu usage from prometheus  is bug?

### ISSUE THREAD

**Issue by hongli-my** [kubernetes/autoscaler#1810] opened 2019-03-22 05:01 UTC
https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/input/history/history_provider.go#L193

container_cpu_usage_seconds_total type is  counter,  use it as  container cpu usage is right?

**Comment by safanaj** [comment] 2019-03-22 07:48
Hi, prometheus is used to collect history real usage, do you think that to use `sum(rate(container_cpu_usage_seconds_total[]))` would be more appropriate ?

**Comment by hongli-my** [comment] 2019-03-22 07:52
I debug  this code: sample get from prometheus very large compare to the sample from metrics-server.

**Comment by bskiba** [comment] 2019-03-22 08:42
Hi there. This is duplicate of #1501. We'll gladly see contributions from someone who can test this with prometheus.

**Closed by bskiba** 2019-03-22 08:42 UTC

**Comment by safanaj** [comment] 2019-03-22 09:04
@bskiba I tested this and yes we should use `rate()` or `irate()` to get values close to what metrics-server is providing.
I can take this and prepare a PR soon

**Comment by bskiba** [comment] 2019-03-22 09:20
That would be great, thanks!
