### ISSUE TITLE
CA priority expander chooses low priorities although there are higher options

### ISSUE THREAD

**Issue by daganida88** [kubernetes/autoscaler#2835] opened 2020-02-16 09:27 UTC
We have available nodes both on the ASG with the 50 priority and on the ASG with 1 priority,
but from time to time, the CA schedule pods on the low priority ASG.

This is the config map:
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-autoscaler-priority-expander
  namespace: kube-system
data:
  priorities: |-
    1:
      - .*
    50:
      - .*int-cluster-az-c-spot20200210134001506600000024*.
      - .*int-cluster-az-b-spot20200210134001540300000029*.
      - .*int-cluster-az-d-spot20200210134001515700000027*.
      - .*int-cluster-az-f-spot20200210134001535700000028*.

this it the CA log in one case this happened:
I0216 08:12:39.489693       1 priority.go:167] priority expander: int-cluster-az-b-spot20200210134001540300000029 chosen as the highest available
I0216 08:12:39.489698       1 priority.go:167] priority expander: int-cluster-az-c-spot20200210134001506600000024 chosen as the highest available
I0216 08:12:39.489701       1 priority.go:167] priority expander: int-cluster-az-d-spot20200210134001515700000027 chosen as the highest available
I0216 08:12:39.489705       1 priority.go:167] priority expander: int-cluster-az-f-spot20200210134001535700000028 chosen as the highest available
**I0216 08:12:39.489714       1 priority.go:167] priority expander: int-cluster-on-demand20200210152512009600000002 chosen as the highest available**
I0216 08:12:51.687213       1 priority.go:167] priority expander: int-cluster-az-b-spot20200210134001540300000029 chosen as the highest available
I0216 08:12:51.687220       1 priority.go:167] priority expander: int-cluster-az-c-spot20200210134001506600000024 chosen as the highest available
I0216 08:12:51.687225       1 priority.go:167] priority expander: int-cluster-az-d-spot20200210134001515700000027 chosen as the highest available
I0216 08:12:51.687230       1 priority.go:167] priority expander: int-cluster-az-f-spot20200210134001535700000028 chosen as the highest available
**I0216 08:12:51.687235       1 priority.go:167] priority expander: int-cluster-on-demand20200210152512009600000002 chosen as the highest available**

**Comment by Pluies** [comment] 2020-07-03 13:31
We're running into the same issue here.

It seems to be related to the `.*` fallback? When switching to using matches that only happen in one of the ASGs, it appears to work properly.

We were setting the following config on the Helm chart:
```
expanderPriorities: |-
  10:
  - ".*"
  50:
  - ".*spot.*"
```

And we were seeing in the logs:
```
I0703 09:55:54.755163       1 priority.go:118] Successfully loaded priority configuration from configmap.
I0703 09:55:54.755258       1 priority.go:167] priority expander: growth-staging-eks-spot-subnet-111111111111111111 chosen as the highest available
I0703 09:55:54.755318       1 priority.go:167] priority expander: growth-staging-eks-spot-subnet-222222222222222222 chosen as the highest available
I0703 09:55:54.755363       1 priority.go:167] priority expander: growth-staging-eks-spot-subnet-333333333333333333 chosen as the highest available
I0703 09:55:54.755411       1 priority.go:167] priority expander: growth-staging-eks-subnet-111111111111111111 chosen as the highest available
I0703 09:55:54.755454       1 priority.go:167] priority expander: growth-staging-eks-subnet-222222222222222222 chosen as the highest available
I0703 09:55:54.755509       1 priority.go:167] priority expander: growth-staging-eks-subnet-333333333333333333 chosen as the highest available
I0703 09:55:54.755561       1 scale_up.go:430] Best option to resize: growth-staging-eks-subnet-333333333333333333
```

Which is wrong – all ASGs are being selected as "highest available", despite three of them matching the higher-priority `.*node.*`. Once all these subnets have been chosen, one is picked at random, and it happens to be the non-spot ones in this case.

We seem to have fixed it by using the following config:
```
expanderPriorities: |-
  10:
  - eks-subnet
  50:
  - eks-spot-subnet
```

And the logs:
```
I0703 10:16:32.246156       1 priority.go:118] Successfully loaded priority configuration from configmap.
W0703 10:16:32.246209       1 priority.go:91] Priority expander: node group growth-staging-eks-subnet-111111111111111111 not found in priority expander configuration. The group won't be used.
W0703 10:16:32.246218       1 priority.go:91] Priority expander: node group growth-staging-eks-subnet-222222222222222222 not found in priority expander configuration. The group won't be used.
W0703 10:16:32.246227       1 priority.go:91] Priority expander: node group growth-staging-eks-subnet-333333333333333333 not found in priority expander configuration. The group won't be used.
I0703 10:16:32.246232       1 priority.go:167] priority expander: growth-staging-eks-spot-subnet-111111111111111111 chosen as the highest available
I0703 10:16:32.246237       1 priority.go:167] priority expander: growth-staging-eks-spot-subnet-222222222222222222 chosen as the highest available
I0703 10:16:32.246241       1 priority.go:167] priority expander: growth-staging-eks-spot-subnet-333333333333333333 chosen as the highest available
I0703 10:16:32.246265       1 scale_up.go:430] Best option to resize: growth-staging-eks-spot-subnet-333333333333333333
```

(The `The group won't be used` message seems to be expected though misleading according to: https://github.com/kubernetes/autoscaler/issues/2768 )

The cluster-autoscaler also correctly uses the non-spot node groups when a pod has set a non-spot nodeSelector, so everything is working as intended with this workaround 👍

**Comment by bruecktech** [comment] 2020-07-10 12:24
This may be the fix for this issue: https://github.com/kubernetes/autoscaler/pull/3308

**Comment by nitrag** [comment] 2020-07-10 14:02
I just noticed a similar issue just last night! 

```
apiVersion: v1
kind: ConfigMap
data:
  priorities: |
    10:
      - .*
    50:
      - pv-platform-master-worker-.*-spot
```

On one pass it will do:
```
I0710 06:03:45.955983       1 priority.go:118] Successfully loaded priority configuration from configmap.
I0710 06:03:45.956005       1 priority.go:167] priority expander: pv-platform-master-worker-gpu-accelerated-p2-xlarge chosen as the highest available
I0710 06:03:45.956011       1 priority.go:167] priority expander: pv-platform-master-worker-gpu-accelerated-p2-xlarge-spot chosen as the highest available
I0710 06:03:45.956023       1 scale_up.go:427] Best option to resize: pv-platform-master-worker-gpu-accelerated-p2-xlarge
I0710 06:03:45.956036       1 scale_up.go:431] Estimated 1 nodes needed in pv-platform-master-worker-gpu-accelerated-p2-xlarge
I0710 06:03:45.956074       1 scale_up.go:533] Final scale-up plan: [{pv-platform-master-worker-gpu-accelerated-p2-xlarge 0->1 (max: 20)}]
I0710 06:03:45.956090       1 scale_up.go:699] Scale-up: setting group pv-platform-master-worker-gpu-accelerated-p2-xlarge size to 1
```

and on the next pass (10 seconds later) it will choose (spot) correctly:
```
I0710 06:03:57.611444       1 priority.go:118] Successfully loaded priority configuration from configmap.
I0710 06:03:57.611461       1 priority.go:167] priority expander: pv-platform-master-worker-gpu-accelerated-p2-xlarge-spot chosen as the highest available
I0710 06:03:57.611474       1 scale_up.go:427] Best option to resize: pv-platform-master-worker-gpu-accelerated-p2-xlarge-spot
I0710 06:03:57.611486       1 scale_up.go:431] Estimated 1 nodes needed in pv-platform-master-worker-gpu-accelerated-p2-xlarge-spot
I0710 06:03:57.611505       1 scale_up.go:533] Final scale-up plan: [{pv-platform-master-worker-gpu-accelerated-p2-xlarge-spot 0->1 (max: 20)}]
I0710 06:03:57.611519       1 scale_up.go:699] Scale-up: setting group pv-platform-master-worker-gpu-accelerated-p2-xlarge-spot size to 1
I0710 06:03:57.611556       1 auto_scaling_groups.go:221] Setting asg pv-platform-master-worker-gpu-accelerated-p2-xlarge-spot size to 1
```

@bruecktech I'm not understanding how removing `break` in your PR resolves the issue. Maybe I just haven't had enough coffee yet though...

**Comment by bruecktech** [comment] 2020-07-10 14:08
The `break` stops the loop over the priorities for a specific expander option / node group. the map of priorities is unordered. so so if the wildcard matches your node groups pv-platform-master-worker-gpu-accelerated-p2-xlarge and pv-platform-master-worker-accelerated-p2-xlarge-spot both end up in a list of best choices and then there's a random fallback strategy to pick one of this list randomly.
The second source of randomness is the map of priorities derived from the config. depending on the order in which it loops over it it will break sooner or later leading to a different list of best choices.

**Comment by nitrag** [comment] 2020-07-10 15:48
I am testing a hot fix version and @bruecktech's fix appears working, no misses to the wrong priority. Thanks!

**Closed** 2020-08-09 16:45 UTC
Labels: lifecycle/rotten

**Comment by nitrag** [comment] 2020-08-27 23:24
@bruecktech I'm testing your fix. I thought it was working for a while but getting mixed results now. I added a long line to show the score. Any ideas?

```
I0827 18:32:55.295578       1 priority.go:118] Successfully loaded priority configuration from configmap.
W0827 18:32:55.295613       1 priority.go:91] Priority expander: node group pv-platform-master-worker-gpu-accelerated-ai-mixed found with score 10
W0827 18:32:55.295625       1 priority.go:91] Priority expander: node group pv-platform-master-worker-gpu-accelerated-ai-mixed-spot found with score 10
I0827 18:32:55.295630       1 priority.go:168] priority expander: pv-platform-master-worker-gpu-accelerated-ai-mixed chosen as the highest available
I0827 18:32:55.295634       1 priority.go:168] priority expander: pv-platform-master-worker-gpu-accelerated-ai-mixed-spot chosen as the highest available
I0827 18:32:55.295641       1 scale_up.go:427] Best option to resize: pv-platform-master-worker-gpu-accelerated-ai-mixed
I0827 18:32:55.295648       1 scale_up.go:431] Estimated 1 nodes needed in pv-platform-master-worker-gpu-accelerated-ai-mixed
I0827 18:32:55.295665       1 scale_up.go:533] Final scale-up plan: [{pv-platform-master-worker-gpu-accelerated-ai-mixed 0->1 (max: 20)}]
I0827 18:32:55.295801       1 scale_up.go:699] Scale-up: setting group pv-platform-master-worker-gpu-accelerated-ai-mixed size to 1
I0827 18:32:55.295814       1 auto_scaling_groups.go:221] Setting asg pv-platform-master-worker-gpu-accelerated-ai-mixed size to 1
```

How is it possible that they both get a score of 10?

```
(base) ➜  terraform-k8s git:(master) kubectl -n kube-system get configmap cluster-autoscaler-priority-expander -o yaml
apiVersion: v1
data:
  priorities: |
    30:
      - pv-platform-master-worker-gpu-accelerated-.*-spot
    30:
      - pv-platform-master-worker-general-purpose-spot
    10:
      - .*
kind: ConfigMap
metadata:
  creationTimestamp: 2020-02-03T19:29:15Z
  name: cluster-autoscaler-priority-expander
```

I also added our own test, which is also failing.
```
    pointivoMatchConfig = `
30:
  - "pv-platform-master-worker-gpu-accelerated-.*-spot"
30:
  - "pv-platform-master-worker-general-purpose-spot"
10:
  - ".*"

        

        eoPV = expander.Option{
		Debug:     "m5a.2xlarge",
		NodeGroup: test.NewTestNodeGroup("zeroscaling-gpu-accelerated-ai-mixed", 10, 1, 1, true, false, "m5a.2xlarge", nil, nil),
	}
	eoPVSpot = expander.Option{
		Debug:     "m5a.4xlarge",
		NodeGroup: test.NewTestNodeGroup("zeroscaling-gpu-accelerated-ai-mixed-spot", 10, 1, 1, true, false, "m5a.4xlarge", nil, nil),
	}

func TestPriorityExpanderPV(t *testing.T) {
	s, _, _, _ := getStrategyInstance(t, pointivoMatchConfig)
	for i := 0; i < 10; i++ {
		ret := s.BestOption([]expander.Option{eoPV, eoPVSpot}, nil)
		assert.Equal(t, *ret, eoPVSpot)
	}
}
```



```
    priority_test.go:147: 
        	Error Trace:	priority_test.go:147
        	Error:      	Not equal: 
        	            	expected: expander.Option{NodeGroup:(*test.TestNodeGroup)(0xc0002b3960), NodeCount:0, Debug:"m5a.2xlarge", Pods:[]*v1.Pod(nil)}
        	            	actual  : expander.Option{NodeGroup:(*test.TestNodeGroup)(0xc0002b39d0), NodeCount:0, Debug:"m5a.4xlarge", Pods:[]*v1.Pod(nil)}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -7,3 +7,3 @@
        	            	   cloudProvider: (*test.TestCloudProvider)(<nil>),
        	            	-  id: (string) (len=36) "zeroscaling-gpu-accelerated-ai-mixed",
        	            	+  id: (string) (len=41) "zeroscaling-gpu-accelerated-ai-mixed-spot",
        	            	   maxSize: (int) 10,
        	            	@@ -13,3 +13,3 @@
        	            	   autoprovisioned: (bool) false,
        	            	-  machineType: (string) (len=11) "m5a.2xlarge",
        	            	+  machineType: (string) (len=11) "m5a.4xlarge",
        	            	   labels: (map[string]string) <nil>,
        	            	@@ -18,3 +18,3 @@
        	            	  NodeCount: (int) 0,
        	            	- Debug: (string) (len=11) "m5a.2xlarge",
        	            	+ Debug: (string) (len=11) "m5a.4xlarge",
        	            	  Pods: ([]*v1.Pod) <nil>
        	Test:       	TestPriorityExpanderPointivo
    priority_test.go:147: 
```

**Comment by bruecktech** [comment] 2020-08-28 06:07
@nitrag which version of CA are you running? it seems this fix is not released in any of the versions yet
your test probably fails because you have test nodes called `zeroscaling...` but your expander config matches `pv-platform-master-worker...`

**Comment by nitrag** [comment] 2020-08-28 15:12
@bruecktech I've pulled `1.15.7` and manually added your PR on top. You're right about the 😫  typo but I'm still having the error. In the test, the actual is correct. Why is the test choosing the wrong expected?

Please see this gist for the full code changes: https://gist.github.com/nitrag/a381083edbcfef5f45b31198617e32ee

**Comment by nitrag** [comment] 2020-08-29 05:16
Well after a long day of troubleshooting I've discovered that (quite obviously now that I see it) the priorities become a map and therefore cannot have the same priority values or else be replaced.

```
data:
  priorities: |
    30:
      - pv-platform-master-worker-gpu-accelerated-.*-spot
    30:
      - pv-platform-master-worker-general-purpose-spot
    10:
      - .*
    15:
      - .*-spot
kind: ConfigMap
```
