### ISSUE TITLE
Cluster Autoscalar does not show ASG Scaling Activity History

### ISSUE THREAD

**Issue by ppruthi** [kubernetes/autoscaler#1402] opened 2018-11-13 18:06 UTC
version: 1.2.3

### Description

ASG Scaling Activity History failure messages like this one:
```
Launching a new EC2 instance. Status Reason: We currently do not have sufficient xx.large capacity in the Availability Zone you requested (xx-xxxx-xx). Our system will be working on provisioning additional capacity. You can currently get xx.large capacity by not specifying an Availability Zone in your request or choosing xx-xxxx-xx. Launching EC2 instance failed.
```

are not surfaced on cluster autoscalar logs to expose why the scale up didn't happen.
Instead the cluster autoscalar logs messages like:

```
pod didn't trigger scale-up (it wouldn't fit if a new node is added)
```

which does not completely reflect whats wrong with the cloud provider.

**Comment by aleksandra-malinowska** [comment] 2018-11-14 01:54
>are not surfaced on cluster autoscalar logs to expose why the scale up didn't happen.
>Instead the cluster autoscalar logs messages like:
>
>pod didn't trigger scale-up (it wouldn't fit if a new node is added)
>which does not completely reflect whats wrong with the cloud provider.

This message means Cluster Autoscaler didn't even request a node, so there was no interaction with ASG, so there could be no error message there.

Newer versions should publish event with more information (predicate that failed with number of affected groups).

**Comment by johanneswuerbach** [comment] 2018-11-15 18:55
This seems to be a duplicate of https://github.com/kubernetes/autoscaler/issues/1263, yes CA currently doesn’t surface ASG scaling failures as AWS doesn’t actually fail the scale-up

**Comment by ppruthi** [comment] 2018-11-16 17:31
@aleksandra-malinowska .. is there anyway to backport the visibility cuz the older version if kubernetes is recommended to run with older versions of autoscalar ?

**Closed** 2019-04-21 16:36 UTC
Labels: aws, cluster-autoscaler, lifecycle/rotten
