### ISSUE TITLE
Azure AKS cluster autoscaler hangs during up scaling

### ISSUE THREAD

**Issue by netiperher** [kubernetes/autoscaler#1661] opened 2019-02-09 10:43 UTC
CloudProvider: Azure AKS
Kubernetes version: 1.11.5
Cluster Autoscaler version: 1.3.5
ACS-Engine version: v0.26.3-aks

In our setup we run an Azure AKS cluster with multiple nodes that each run a single pod requiring all resources on the node. The pods are part of a statefulset that we scale quite aggressively from 2 to 20 and then back to 2 replicas at regular intervals.

Sometimes (<10%) when scaling up nodes the whole process takes considerable longer time than usual and this is often associated with the autoscaler pod crashing. When everything works normally the average time for us is 21 minutes when going from 2 to 20 nodes and when not working scaling up can take as long as 75 minutes.

Attached logs and screenshot of the `cluster_autoscaler_nodes_count` metric for when the upscaling stopped working after scaling up to 16 nodes and then nothing happens for 30 minutes.

![screenshot 2019-02-07 at 18 40 29](https://user-images.githubusercontent.com/45091747/52519612-3fc60200-2c5e-11e9-8c36-93b5d8002723.png)

Logs before crash (16:30 to 17:15)
[autoscaler-azure-cluster-autoscaler-7c8df96664-h8fs4-before.log](https://github.com/kubernetes/autoscaler/files/2847708/autoscaler-azure-cluster-autoscaler-7c8df96664-h8fs4-before.log)

Logs after crash (17:15 to 17:45)
[autoscaler-azure-cluster-autoscaler-7c8df96664-h8fs4-after.log](https://github.com/kubernetes/autoscaler/files/2847710/autoscaler-azure-cluster-autoscaler-7c8df96664-h8fs4-after.log)

Relevant log lines are around this lines
```
E0207 16:49:23.319809       1 static_autoscaler.go:283] Failed to scale up: failed to increase node group size: Code="" Message=""
```

cc @feiskyer

**Comment by feiskyer** [comment] 2019-02-11 01:27
@netiperher Thanks for reporting the issue.

> Sometimes (<10%) when scaling up nodes the whole process takes considerable longer time than usual and this is often associated with the autoscaler pod crashing.

Have you noticed why autoscaler pod is crashing? e.g. what errors are reporting then?

**Comment by netiperher** [comment] 2019-02-11 07:35
When this happens (also in this example) the autoscaler is killed by the liveness probe. We use the default values of 3 failed probe at 10 second interval.

**Comment by netiperher** [comment] 2019-02-11 15:22
So maybe there are two problems in this issue. One is that the autoscaler was killed, possibly due to deleting the VM took longer than normal.
The other issue that is also more relevant for us is why the autoscaler was stalled for 25 minutes between ~16:50 and 17:15. Somehow it failed during scale up from 16 to 20 nodes. But then after 15 minutes the machines are finally up, but then the autoscaler tries to remove them.

```
I0207 16:47:24.785972       1 scale_up.go:466] Final scale-up plan: [{nodepool1 16->20 (max: 20)}]
E0207 16:49:23.319809       1 static_autoscaler.go:283] Failed to scale up: failed to increase node group size: Code="" Message=""
I0207 16:49:33.647785       1 scale_up.go:291] Upcoming 4 nodes
I0207 16:49:54.595614       1 static_autoscaler.go:160] 4 unregistered nodes present
...
I0207 17:04:43.328124       1 utils.go:377] Removing unregistered node 
azure:///subscriptions/03388b22-6519-4128-939d-c24e9890b048/resourceGroups/MC_saas-aks_saas-aks_westeurope/providers/Microsoft.Compute/virtualMachines/aks-nodepool1-16716784-19
```

So one question is why the scale up failed? There is no error message to understand why this happens. Then why are the nodes removed when they are finally up?

**Comment by feiskyer** [comment] 2019-02-19 09:05
There's something wrong in error message handling, just filed a PR #1703 to fix it.

**Comment by feiskyer** [comment] 2019-02-20 02:47
@netiperher When digging the root causes, the error message of `Code="" Message=""` is actually because  CA is using old Azure SDK versions. While it would need sometime for picking new changes, could you check the errors from Azure portal (e.g. from activity log)?

**Comment by netiperher** [comment] 2019-02-20 07:22
@feiskyer thanks for the update, I'll check in the Azure portal the next time it happens (it has been 7 days now since the last time). If you have a new version with improved logging I'm willing to test that as well.

**Comment by feiskyer** [comment] 2019-02-20 09:17
@netiperher sure, but it's not easy because the dependent packages (in new version) are actually conflicting with current packages in vendor (in old version). Would need to verify whether it works with overriding vendors for each CA releases.

**Comment by netiperher** [comment] 2019-02-21 11:08
@feiskyer can you re-open this until we found the issue?
Do you have any plans to backport #1703 to 1.3 branch? Otherwise we'll just check for errors in the Azure portal as you recommended.

**Comment by feiskyer** [comment] 2019-02-21 12:19
Yep, this should be kept open until cherry-picked.

/reopen

**Comment by feiskyer** [comment] 2019-02-21 12:22
@netiperher Have you got the error messages from activity log?

**Comment by netiperher** [comment] 2019-02-22 07:30
@feiskyer this is the deployment error that I see in the portal, in this instance (Feb 7) I see the following error repeated for each of the 4 machines that failed to scale up (i.e. 16 to 20)
```
  {
    "id": "/subscriptions/.../resourceGroups/MC_XXX/providers/Microsoft.Resources/deployments/479d4684-5569-4eda-b872-5ff6484d72c5/operations/B169F00F5246117D",
    "operationId": "B169F00F5246117D",
    "properties": {
      "provisioningOperation": "Create",
      "provisioningState": "Failed",
      "timestamp": "2019-02-07T16:49:11.809837Z",
      "duration": "PT1M36.8829027S",
      "trackingId": "03594205-96bb-4bb4-b628-6f909dcd9477",
      "serviceRequestId": "24f69ad1-7e4f-424b-a600-1abefe09dfd4",
      "statusCode": "Conflict",
      "statusMessage": {
        "status": "Failed",
        "error": {
          "code": "ResourceDeploymentFailure",
          "message": "The resource operation completed with terminal provisioning state 'Failed'.",
          "details": [
            {
              "code": "NetworkingInternalOperationError",
              "message": "Unknown network allocation error."
            }
          ]
        }
      },
      "targetResource": {
        "id": "/subscriptions/.../resourceGroups/MC_XXX/providers/Microsoft.Compute/virtualMachines/aks-nodepool1-16716784-16",
        "resourceType": "Microsoft.Compute/virtualMachines",
        "resourceName": "aks-nodepool1-16716784-16"
      }
    }
  },
```

**Comment by feiskyer** [comment] 2019-02-22 08:24
Not sure what's this error `Unknown network allocation error` means. Is the error still existing? If so, please file a support ticket.

**Comment by netiperher** [comment] 2019-02-22 08:33
Sure, I will file an Azure support ticket if it happens again, but is there anything that can be done in the cluster autoscaler so that it doesn't stop the up-scaling for 30 minutes when there are Azure issues?

**Comment by feiskyer** [comment] 2019-02-22 09:02
I'm afraid it's not easy to catch all exceptions. e.g. we have met a few cases that some network interfaces and SLB are in error states. CA couldn't catch those, it requires the admin to fix them manually.

**Comment by feiskyer** [comment] 2019-03-08 11:34
All cherry picks have been merged now.

@netiperher Feel free to re-open it if you still have issues.

/close

**Closed by feiskyer** 2019-03-08 11:34 UTC
Labels: azure, cluster-autoscaler
