### ISSUE TITLE
More expensive instance type given priority

### ISSUE THREAD

**Issue by drewhemm** [kubernetes/autoscaler#1821] opened 2019-03-25 13:19 UTC
Running version 1.3.7 on AWS EKS, I have multiple node groups and two in particular are i3.2xlarge and r5.2xlarge. Although they are identical in CPU cores and memory, the latter are cheaper to run and I am wondering why CA always seems to spawn i3.2xlarge instead. 

What is the determining factor here and can I influence it in any way?

I am using spot instances, but not sure that is relevant. 

If I manually set the min size on the ASG, CA will respect that and scheduled the pods onto those nodes, but I would like CA to automatically choose the cheapest instance type available when a pod can fit on either.

**Comment by MaciekPytel** [comment] 2019-03-26 13:19
The function that chooses which NodeGroup (ASG) to scale-up is called expander. You can set which expander you want to use with a flag and the available options are documented here https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-are-expanders. Note that 'priority' is currently in development and not included in any released version. 

What you're requesting is what 'price' expander is doing. Unfortunately this is not trivial to implement and currently it's only supported in GCP.

**Comment by Jeffwan** [comment] 2019-08-01 23:54
@drewhemm priority expander has been released in the latest version and you can use it to control priority now.  To figure out root cause for i3.2xlarge selection, you need to check your CA configuration, for example, least wastes or something else. Maybe i3.2xlarge is always qualified.

**Comment by drewhemm** [comment] 2019-08-02 07:15
Thanks! I will give the latest version a spin and report back.

**Closed** 2019-09-01 07:44 UTC
Labels: lifecycle/rotten
