### ISSUE TITLE
gophercloud blocks vendor updating

### ISSUE THREAD

**Issue by nilo19** [kubernetes/autoscaler#3414] opened 2020-08-07 02:50 UTC
When I try `update-vendor.sh` against k8s master, the following error blocks it:
```
go: k8s.io/autoscaler/cluster-autoscaler/cloudprovider/magnum imports
        k8s.io/autoscaler/cluster-autoscaler/cloudprovider/magnum/gophercloud: k8s.io/autoscaler/cluster-autoscaler/cloudprovider/magnum/gophercloud@v0.0.0-20200806155343-b13e8de55f9d: parsing go.mod:
        module declares its path as: github.com/gophercloud/gophercloud
                but was required as: k8s.io/autoscaler/cluster-autoscaler/cloudprovider/magnum/gophercloud
```
@tghartland

/kind bug

**Comment by tghartland** [comment] 2020-08-07 10:25
Thanks for finding this. The linked PR should fix this issue but because the vendoring process seems to always pull a fresh copy of the autoscaler master, it ignores any local changes so the fix needs to be merged before it can be confirmed to work.

If it doesn't work the plan B will be to just delete the go.mod from the gophercloud copy.

**Closed** 2020-08-07 12:24 UTC
Labels: kind/bug
