### ISSUE TITLE
[Cluster Autoscaler] --IgnoreTaint=sometaint proposal.

### ISSUE THREAD

**Issue by SleepyBrett** [kubernetes/autoscaler#1350] opened 2018-10-25 14:59 UTC
For our clusters we use Immutable nodes and therefore certain changes require us to roll over our node pools. We currently use the following system.

1) We apply the new node config to the cloud provider, assuring that new nodes that appear will have the new configuration.

2) We taint all the existing nodes in the pool with `recycle=true:NoSchedule` assuring that any pods that get drained don't just end up on another old node leading to constant leapfrogging.

3) We have a pod that looks for the recycle taint, when it finds one it drains the node and calls the cloud provider to terminate it.

The problem we are finding is that the cluster autoscale in this scenario will not actually scale up these node pools. My assumption is that since it sees all the nodes in the pool as tainted with `recycle=true:NoSchedule` it has decided that any node that comes from scaling that pool up will result in the taint. This makes a certain amount of sense.

I'm proposing a flag that allows us to pass taints that should be ignored by the cluster autoscaler for purposes of scaleup.

Our current workaround is to manually go into the cloud provider and scale the group up by 1 so that it will have one non-tainted "new configuration" to disrupt the behavior.

**Comment by aleksandra-malinowska** [comment] 2018-10-25 15:07
This is a duplicate of #789, and a different implementation (always looking at node group's template) is in #1021. There are some issues with how it should work exactly, though. @MaciekPytel has more context on this.

**Comment by SleepyBrett** [comment] 2018-10-25 15:12
Yeah the template wouldn't cover this particular case because it's not responsible for tainting the node. It does not solve some of those other cases though.

**Comment by aleksandra-malinowska** [comment] 2018-10-25 16:03
> Yeah the template wouldn't cover this particular case because it's not responsible for tainting the node. 

On GCE and GKE template has the taints:) if it doesn't have them, Cluster Autoscaler can't accurately predict what a node would look like and scale up from 0 won't work correctly.

**Comment by SleepyBrett** [comment] 2018-10-31 18:47
ok so on one cloud provider the template does. But no other cloud provider seems to.

**Comment by MaciekPytel** [comment] 2018-10-31 20:17
It's up to cloudprovider implementation to provide accurate template (however it does it, I know kops on AWS does it very differently than GCE), but I don't think it matters for this issue anyway.

As I wrote on https://github.com/kubernetes/autoscaler/pull/1021 I generally don't agree with that approach. At the same time I think adding taints in runtime is a valid use-case and we don't support it at all in CA. So I'm +1 for your feature request. 

My only comment is I'd prefer a different mechanism for identifying taints to ignore. Presumably the list of those taints may be long and may change at runtime and flags are poorly suited for both those things. In https://github.com/kubernetes/autoscaler/pull/1021#issuecomment-430645477 I proposed just ignoring any taint that matches prefix. This avoids the inherent problems of flags, but it's a rather ugly hack. I'll see if I can come up with something better. In the meantime any ideas on what would be the best way to specify this are welcome.

**Comment by SleepyBrett** [comment] 2018-11-01 15:56
Prefixing or maybe a list in a configmap (that get's reloaded from time to time) both seem reasonable.

**Comment by aermakov-zalando** [comment] 2018-11-12 11:11
I've added a comment in #1021 (sorry, I was busy with other stuff) because I still think that it's worth solving correctly instead of hacking around weird logic with yet another non-intuitive flag. Would you mind having a look?

**Comment by SleepyBrett** [comment] 2018-11-13 23:59
Sorry your pull is laden with jargon that I don't understand. 

I will say this. Taints are not something that the aws template is going to expose to you unless you dig into the user data and look at the configuration on the kubelet which may be flags/config .. and then bringing into consideration dynamic kublet config etc etc. This seems very fraught. The scale from 0 scenario seems very complicated. If you really wanted it to be simple why not just let the users provide you with a configuration file that lists the pools and what they expect the nodes allocatable / labels / taints to be. Maybe with a nice little script that they can point at a template. People can automate updating that if they decide they want to change some bit of configuration.

The cluster autoscaler code around the simulation is already crazy complicated. Adding a whole subsystem to find the right kubeletconfig, parse it and process it only for it to be potentially wrong (if active systems on the cluster modify some of those values while the node is still getting ready).  We've proposed a system internally where we start a node tainted unschedulable until certain of our deamonsets become ready at which time automation will remove that taint. Under that kind of system looking at the user data will lead to the wrong conclusions.

If anything providing a list of taints or a taint prefix to be ignored seems like the simplest solution to my problem.

**Comment by aermakov-zalando** [comment] 2018-11-14 12:12
CA already supports configuring taints and labels on the ASG, unfortunately it also has the automagic behaviour that 'helpfully' tries to pick up the data from the existing nodes, leading to issues similar to what you have. Since the same thing affects labels, which cannot be easily ignored due to potential effect on node selectors, I'm arguing for solving this in a cleaner way instead of hacks like `--ignore-taint`.

**Comment by SleepyBrett** [comment] 2018-11-16 06:01
Cleaner only on one cloud provider without a serious amount of effort.

**Comment by SleepyBrett** [comment] 2019-03-14 14:35
I have a thought I'd like to propose. Could there be a way that users could, optionally, provide a description of what a node that belongs to a specific autoscaling group. If that description is not present the autoscaler should fall back to it's current behavior (looking at the latest(?) live node in that pool and assuming the next will look like that). I propose that that description should be in the form of a kubernetes node object.

In this way if you start a node in a tainted state or if a node falls into a tainted state due to some kind of node status checking or other process. The cluster autoscaler can know that if it scales up it will get a node in an untainted and therefore scheduled state.

**Comment by cjbradfield** [comment] 2019-04-03 17:49
+1 on the general issue at hand (cluster-autoscaler not playing well with taints). I also work with clusters that have a workflow that apply taints to nodes after they enter the cluster.

@SleepyBrett Although having template nodes in a ConfigMap would work, it seems to me that all that is really missing is a way to identify the taints that are attached to the node at cluster join and maybe the labels. Anything else shouldn't be mutable after the node enters the cluster and the autoscaler should be able to use those. I'd rather not have to update a ConfigMap whenever I change instance types in my ASGs which I would have to do in your final proposal.

So, I personally prefer your first suggestion. --ignore-taint(s)/labels would work well for my purposes (or a list of taints to ignore in a ConfigMap). The taints from TaintNodesByCondition should probably be ignored regardless.

I'd be willing to give writing a PR for either approach a go if we can decide which way to go.

**Closed** 2019-05-15 09:18 UTC
Labels: cluster-autoscaler, kind/feature, lifecycle/rotten

**Comment by LucaLanziani** [comment] 2021-05-13 07:12
Hello, first of all thanks for adding this functionality.

I've noticed that the flag is not part of the list present here: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-are-the-parameters-to-ca

Is that in purpose?
Adding the flag there will help a lot of people to discover it and to understand the intended use of it, I myself before reading this other issue https://github.com/kubernetes/autoscaler/issues/3985 I was a bit confused on how to use it correctly.

I would be more than happy to help writing that part of the documentation if the information on the issue 3985 are enough to write the description of the flag.

Let me know if you prefer me to open a different issue for tracking the documentation of the flag.

Thanks,
Luca
