### ISSUE TITLE
VerticalPodAutoscaler not compatible with k8s 1.18.x libraries 

### ISSUE THREAD

**Issue by tariq1890** [kubernetes/autoscaler#3219] opened 2020-06-11 17:17 UTC
We are trying to vendor in the latest Kubernetes client-libraries. We are blocked from doing so as we also depend on VPA as a library

**Comment by mcristina422** [comment] 2020-06-12 03:18
Duplicate of https://github.com/kubernetes/autoscaler/issues/3097
I updated them here https://github.com/kubernetes/autoscaler/pull/3098

**Closed** 2020-07-22 15:52 UTC
