### ISSUE TITLE
CA does not enforce max node count

### ISSUE THREAD

**Issue by vladimirtiukhtin** [kubernetes/autoscaler#5691] opened 2023-04-17 10:44 UTC
**Which component are you using?**:

cluster-autoscaler

**What version of the component are you using?**:

1.26.2

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.2", GitCommit:"fc04e732bb3e7198d2fa44efa5457c7c6f8c0f5b", GitTreeState:"clean", BuildDate:"2023-02-22T13:39:03Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.2", GitCommit:"fc04e732bb3e7198d2fa44efa5457c7c6f8c0f5b", GitTreeState:"clean", BuildDate:"2023-02-22T13:32:22Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:

Hetzner

**What did you expect to happen?**:

When args updated to --nodes=0:0:.. I expect CA to kill all nodes in the cluster

**What happened instead?**:

Nothing. Nodes keep running as they were

**How to reproduce it (as minimally and precisely as possible)**:

- Set number of nodes to some value like `--nodes=1:3:CX21:NBG1:pool1`. Wit until cluster scales up. Update args to `--nodes=0:0:CX21:NBG1:pool1`

**Comment by comeonyo** [comment] 2023-04-18 01:12
Did the CA pod restart when you change the args value?

**Comment by vladimirtiukhtin** [comment] 2023-04-18 06:07
@comeonyo yes of course. I guess it does not kill nodes because there are workloads running, but I need to force it to save money over night

**Comment by comeonyo** [comment] 2023-04-18 12:27
@vladimirtiukhtin 

1. How long did you wait for the scale down? 
To scale down, CA checks node usage for 10 minutes. (I think you already know it.)

2. Are there any Pods not running by the Deployment?

3. Do you have Deamonsets?

4. Do you have pods that using local storage?

5. (If possible) Please, upload yaml of CA deployment without sensitive information.

**Comment by elmiko** [comment] 2023-05-17 11:18
@vladimirtiukhtin i think this is working as intended, when the node count is beyond the autoscaler limits it will not delete, or create, nodes to achieve those levels.

**Comment by vladimirtiukhtin** [comment] 2023-05-17 12:36
I don't consider it a bug anymore, thanks @elmiko. But similar to `--enforce-node-group-min-size` we may like `--enforce-node-group-max-size`. Otherwise people have to create external to CA scripts to delete nodes

**Comment by elmiko** [comment] 2023-05-17 13:25
> But similar to --enforce-node-group-min-size we may like --enforce-node-group-max-size

i think this is a nice idea for a feature, i think we should propose it as a separate issue/proposal though. if you don't mind, i will close this issue.

**Comment by elmiko** [comment] 2024-01-26 13:58
unless there is someone to champion this feature, we should probably close it to reduce the backlog. it's a nice idea, but i don't recall seeing other requests for it recently.

**Closed** 2024-04-20 15:54 UTC
Labels: area/cluster-autoscaler, kind/bug, lifecycle/rotten, area/core-autoscaler
