### ISSUE TITLE
"Pod is blocking scale down because it’s not backed by a controller" but the pod is a jenkins agent running a job

### ISSUE THREAD

**Issue by FranAguiar** [kubernetes/autoscaler#5434] opened 2023-01-20 08:54 UTC
**Which component are you using?**:

Cluster autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

This is my use case, jenkins agents created to run jobs cause the autoscaler rise a warning that a pod is blocking the scale down because is not backed by a controller, those agents eventually will finish the job and the autoscaler will be able to shutdown the node. Is not a big deal but is annoying to see that warning time to time and have to check if it is real or not

**Describe the solution you'd like.**:
An annotation like "cluster-autoscaler.kubernetes.io/safe-to-evict": "true" to said to the autoscaler to wait or ignore the pod without controller and not shutdown the node

**Comment by x13n** [comment] 2023-01-30 10:28
I'm not sure I follow. Do you think the issue is that the jenkins pod should not block node removal or is it just that the logs are annoying?

**Comment by FranAguiar** [comment] 2023-01-30 10:45
Hi, correct, I mean that the log is annoying. I know the pod will end its task eventually, I would like to have an option to say to the autoscaler "I know about this pod without a controller, do not warn me about it and not shutdown the node"

**Comment by darrenbeck-te** [comment] 2023-06-15 11:36
@FranAguiar Did you find a solution to this issue?

**Comment by FranAguiar** [comment] 2023-06-26 12:05
> @FranAguiar Did you find a solution to this issue?

No, we are just ignoring the warning :(

**Comment by gp187** [comment] 2023-08-01 07:16
Is there a way to find the POD that is preventing scale down?

**Comment by lauraseidler** [comment] 2023-08-21 15:42
We have the same issue - I was expecting this warning to go away by annotating the pod as not `cluster-autoscaler.kubernetes.io/safe-to-evict: "false"`, but this did not help. 

I think the reason is that the auto-scaler first [checks for a controller](https://github.com/kubernetes/autoscaler/blob/538994707fbfe7207155832c3b3cc8efb286ebfa/cluster-autoscaler/utils/drain/drain.go#L130-L132) and only at the end [checks for the annotation](https://github.com/kubernetes/autoscaler/blob/538994707fbfe7207155832c3b3cc8efb286ebfa/cluster-autoscaler/utils/drain/drain.go#L145-L147).

IMO, it would make sense to flip this, and check for the annotation first - that way, pods can be marked as safe to evict no matter what, and can generate always the same warning, which will also allow to essentially "ignore" all other warnings. 

This would also be helpful for users of managed k8s services - e.g. we are using GKE, which flags "pod not backed by controller" as a warning, but not "pod marked as not safe to evict".

@x13n as you have commented previously - does that seem reasonable? Would a PR for that be considered?

**Comment by x13n** [comment] 2023-08-23 14:16
Changing the order of conditions would only replace one warning with another in that case: the scale down is blocked, it's just now it will be because the pod has `cluster-autoscaler.kubernetes.io/safe-to-evict: "false"` annotation.

**Comment by x13n** [comment] 2023-08-28 14:46
Ah, I see, thanks for clarifying. That makes sense to me - feel free to assign me a PR if you'd like to change the ordering of these conditions.

**Closed** 2023-09-01 10:14 UTC
Labels: cluster-autoscaler, kind/feature, lifecycle/rotten
