### ISSUE TITLE
Convert resources to a more human relevant SI

### ISSUE THREAD

**Issue by jacobeatsspam** [kubernetes/autoscaler#7417] opened 2024-10-21 17:18 UTC
**Which component are you using?**:

VPA

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

Yes. VPA memory recommendations are applied as kilobytes (`k`, the non-binary 1000 byte) and it's not very relevant to the humans that are reading the podspec later.

**Describe the solution you'd like.**:

Convert to the units to highest SI suffix without decimal places.

**Describe any alternative solutions you've considered.**:

N/A

**Comment by adrianmoisey** [comment] 2024-10-21 19:27
/area vertical-pod-autoscaler

This looks like a dupe of https://github.com/kubernetes/autoscaler/issues/7094

**Comment by omerap12** [comment] 2024-10-22 09:50
I’m happy to help with that if needed.

**Comment by adrianmoisey** [comment] 2024-10-22 11:52
Go for it!
/assign omerap12

**Closed** 2024-11-07 15:19 UTC
Labels: area/vertical-pod-autoscaler, kind/feature
