### ISSUE TITLE
Latest Helm Chart (9.20.0) breaking for AWS

### ISSUE THREAD

**Issue by mattaltberg** [kubernetes/autoscaler#5128] opened 2022-08-25 13:32 UTC
**Which component are you using?**: Autoscaler Helm Chart

**What version of the component are you using?**: 9.20.0

Component version:

**What k8s version are you using (`kubectl version`)?**: 1.22

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", GitCommit:"f59f5c2fda36e4036b49ec027e556a15456108f0", GitTreeState:"clean", BuildDate:"2022-01-19T17:33:06Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.10-eks-84b4fe6", GitCommit:"cc6a1b4915a99f49f5510ef0667f94b9ca832a8a", GitTreeState:"clean", BuildDate:"2022-06-09T18:24:04Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

**What environment is this in?**: AWS EKS

**What did you expect to happen?**: Autoscaler to run without crashing

**What happened instead?**: Autoscaler pod stuck in CrashLoopBackoff

**How to reproduce it (as minimally and precisely as possible)**: Upgrade from 9.19.4 to 9.20.0 without changing values.yml

**Anything else we need to know?**: Image Tag used: v1.22.0, autodiscovery enabled, cloudProvider set to aws
Logs:
```
I0825 13:15:27.089719       1 reflector.go:219] Starting reflector *v1.Pod (1h0m0s) from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:188
I0825 13:15:27.089735       1 reflector.go:255] Listing and watching *v1.Pod from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:188
I0825 13:15:27.090018       1 reflector.go:219] Starting reflector *v1.Pod (1h0m0s) from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:212
I0825 13:15:27.090063       1 reflector.go:255] Listing and watching *v1.Pod from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:212
I0825 13:15:27.090243       1 reflector.go:219] Starting reflector *v1.Node (1h0m0s) from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:246
I0825 13:15:27.090281       1 reflector.go:255] Listing and watching *v1.Node from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:246
I0825 13:15:27.090513       1 reflector.go:219] Starting reflector *v1.Node (1h0m0s) from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:246
I0825 13:15:27.090599       1 reflector.go:255] Listing and watching *v1.Node from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:246
I0825 13:15:27.090765       1 reflector.go:219] Starting reflector *v1beta1.PodDisruptionBudget (1h0m0s) from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:309
I0825 13:15:27.090846       1 reflector.go:255] Listing and watching *v1beta1.PodDisruptionBudget from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:309
I0825 13:15:27.091176       1 reflector.go:219] Starting reflector *v1.DaemonSet (1h0m0s) from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:320
I0825 13:15:27.091215       1 reflector.go:255] Listing and watching *v1.DaemonSet from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:320
I0825 13:15:27.091386       1 reflector.go:219] Starting reflector *v1.ReplicationController (1h0m0s) from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:329
I0825 13:15:27.091424       1 reflector.go:255] Listing and watching *v1.ReplicationController from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:329
I0825 13:15:27.091645       1 reflector.go:219] Starting reflector *v1.Job (1h0m0s) from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:338
I0825 13:15:27.091680       1 reflector.go:255] Listing and watching *v1.Job from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:338
I0825 13:15:27.091864       1 reflector.go:219] Starting reflector *v1.ReplicaSet (1h0m0s) from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:347
I0825 13:15:27.091950       1 reflector.go:255] Listing and watching *v1.ReplicaSet from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:347
I0825 13:15:27.092182       1 reflector.go:219] Starting reflector *v1.StatefulSet (1h0m0s) from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:356
I0825 13:15:27.092196       1 reflector.go:255] Listing and watching *v1.StatefulSet from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:356
W0825 13:15:27.109697       1 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0825 13:15:27.150362       1 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
I0825 13:15:27.188121       1 cloud_provider_builder.go:29] Building aws cloud provider.
F0825 13:15:27.188305       1 aws_cloud_provider.go:348] Couldn't open cloud provider configuration /etc/gce.conf: &fs.PathError{Op:"open", Path:"/etc/gce.conf", Err:0x2}
```

**Comment by BastienM** [comment] 2022-08-25 13:52
#5105 introduces the following change that is breaking the Chart due to a default value:
```
# charts/cluster-autoscaler/templates/deployment.yaml
            {{- if .Values.cloudConfigPath }}
            - --cloud-config={{ .Values.cloudConfigPath }}
            {{- end }}
            
# autoscaler/charts/cluster-autoscaler/values.yaml
cloudConfigPath: /etc/gce.conf
```

**Comment by rlister** [comment] 2022-08-25 14:23
Workaround is to set value `cloudConfigPath=false`.

**Comment by ymatsiuk** [comment] 2022-08-25 15:10
> Should this be set to default to false then?

There might be a risk of breaking `gce` implementation in this case

**Comment by mattaltberg** [comment] 2022-08-25 15:14
But then the current default breaks all other other implementations.

**Comment by BastienM** [comment] 2022-08-25 15:31
Moving to a map for `cloudConfigPath` and have the template do a lookup on it with `cloudProvider` value could be the most generic approach IMO.

```yaml

# charts/cluster-autoscaler/values.yaml
cloudConfigPath:
  aws: ...
  gce: /etc/gce.conf

# charts/cluster-autoscaler/templates/deployment.yaml
command:
  - ./cluster-autoscaler
  - --cloud-provider={{ .Values.cloudProvider }}
  - --cloud-config={{ .Values.cloudConfigPath[.Values.cloudProvider] }}
```

**Comment by mattaltberg** [comment] 2022-08-25 15:47
Here's the strange part though... `cloudConfigPath` is only used when `cloudProvider` is `aws` or `magnum`

```
# charts/cluster-autoscaler/templates/deployment.yaml
       {{- if eq .Values.cloudProvider "aws" }}
            {{- if .Values.autoDiscovery.clusterName }}
            - --node-group-auto-discovery=asg:tag={{ tpl (join "," .Values.autoDiscovery.tags) . }}
            {{- end }}
            {{- if .Values.cloudConfigPath }}
            - --cloud-config={{ .Values.cloudConfigPath }}
            {{- end }}
          {{- else if eq .Values.cloudProvider "gce" }}
          {{- if .Values.autoscalingGroupsnamePrefix }}
            {{- range .Values.autoscalingGroupsnamePrefix }}
            - --node-group-auto-discovery=mig:namePrefix={{ .name }},min={{ .minSize }},max={{ .maxSize }}
            {{- end }}
          {{- end }}
          {{- else if eq .Values.cloudProvider "magnum" }}
            {{- if .Values.autoDiscovery.clusterName }}
            - --cluster-name={{ .Values.autoDiscovery.clusterName }}
            - --node-group-auto-discovery=magnum:role={{ tpl (join "," .Values.autoDiscovery.roles) . }}
            {{- else }}
            - --cluster-name={{ .Values.magnumClusterName }}
            {{- end }}
          {{- else if eq .Values.cloudProvider "clusterapi" }}
            {{- if or .Values.autoDiscovery.clusterName .Values.autoDiscovery.labels }}
            - --node-group-auto-discovery=clusterapi:{{ template "cluster-autoscaler.capiAutodiscoveryConfig" . }}
            {{- end }}
            {{- if eq .Values.clusterAPIMode "incluster-kubeconfig"}}
            - --cloud-config={{ .Values.clusterAPICloudConfigPath }}
            {{- else if eq .Values.clusterAPIMode "kubeconfig-incluster"}}
            - --kubeconfig={{ .Values.clusterAPIWorkloadKubeconfigPath }}
            - --clusterapi-cloud-config-authoritative
            {{- else if eq .Values.clusterAPIMode "kubeconfig-kubeconfig"}}
            - --kubeconfig={{ .Values.clusterAPIWorkloadKubeconfigPath }}
            - --cloud-config={{ .Values.clusterAPICloudConfigPath }}
            {{- else if eq .Values.clusterAPIMode "single-kubeconfig"}}
            - --kubeconfig={{ .Values.clusterAPIWorkloadKubeconfigPath }}
            {{- end }}
          {{- else if eq .Values.cloudProvider "azure" }}
            {{- if .Values.autoDiscovery.clusterName }}
            - --node-group-auto-discovery=label:cluster-autoscaler-enabled=true,cluster-autoscaler-name={{ .Values.autoDiscovery.clusterName }}
            {{- end }}
          {{- end }}
          {{- if eq .Values.cloudProvider "magnum" }}
            - --cloud-config={{ .Values.cloudConfigPath }}
          {{- end }}
          {{- range $key, $value := .Values.extraArgs }}
            {{- if not (kindIs "invalid" $value) }}
            - --{{ $key | mustRegexFind "^[^_]+" }}={{ $value }}
            {{- else }}
            - --{{ $key | mustRegexFind "^[^_]+" }}
            {{- end }}
          {{- end }}
```

so it's not like gce is even currently using the config path...

**Comment by BastienM** [comment] 2022-08-25 15:54
It being used here [charts/cluster-autoscaler/templates/podsecuritypolicy.yaml](https://github.com/kubernetes/autoscaler/blob/2542e8c884a8e25634d3b8f43243fa8706007f30/charts/cluster-autoscaler/templates/podsecuritypolicy.yaml):
```yaml
{{- if eq .Values.cloudProvider "gce" }}
  allowedHostPaths:
    - pathPrefix: {{ .Values.cloudConfigPath }}
{{- end }}
```

**Comment by mattaltberg** [comment] 2022-08-25 16:12
Building on your idea for a map, what about this in deployment.yaml:

```yaml
{{- if .Values.cloudConfigPath[.Values.cloudProvider] }}
- --cloud-config={{ .Values.cloudConfigPath[.Values.cloudProvider] }}
{{- end }}
```

**Comment by laupow** [comment] 2022-08-25 18:46
Confirmed on EKS 1.21. 

Rolling back the cluster-autoscaler chart to 9.19.4 is also a valid mitigation.

**Comment by carterbury** [comment] 2022-08-26 17:37
> Yep... that's 3 hours of my life I'm never getting back...

For me it was 5hrs before I finally figured it out by rolling back to 9.19.4 then finding this post when I was going to open the issue.

**Comment by muratso** [comment] 2022-08-26 19:57
Confirmed on EKS 1.22
.
Rolled back to 9.14.4 and it's working like a charm. :(

**Closed** 2022-08-30 08:59 UTC
Labels: kind/bug
