### ISSUE TITLE
vpa-admission-controller- not created

### ISSUE THREAD

**Issue by dvohra** [kubernetes/autoscaler#2810] opened 2020-02-10 01:52 UTC
1. Installed metrics server.

```
C:\EKS>kubectl -n kube-system get deployment/metrics-server
NAME             READY   UP-TO-DATE   AVAILABLE   AGE
metrics-server   1/1     1            1           105m

```
2. Downloaded autoscaler.
```

C:\EKS>git clone https://github.com/kubernetes/autoscaler.git
Cloning into 'autoscaler'...
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 95628 (delta 0), reused 0 (delta 0), pack-reused 95627R
Receiving objects: 100% (95628/95628), 94.50 MiB | 2.05 MiB/s, done.

Resolving deltas: 100% (60577/60577), done.
Updating files: 100% (20298/20298), done.
```
3. Installed  VPA.

```
C:\EKS>kubectl apply -f  autoscaler\vertical-pod-autoscaler\deploy\
deployment.apps/vpa-admission-controller created
service/vpa-webhook created
serviceaccount/vpa-recommender created
deployment.apps/vpa-recommender created
serviceaccount/vpa-updater created
deployment.apps/vpa-updater created
customresourcedefinition.apiextensions.k8s.io/verticalpodautoscalers.autoscaling
.k8s.io created
customresourcedefinition.apiextensions.k8s.io/verticalpodautoscalercheckpoints.a
utoscaling.k8s.io created
customresourcedefinition.apiextensions.k8s.io/verticalpodautoscalers.autoscaling
.k8s.io configured
customresourcedefinition.apiextensions.k8s.io/verticalpodautoscalercheckpoints.a
utoscaling.k8s.io configured
customresourcedefinition.apiextensions.k8s.io/verticalpodautoscalers.poc.autosca
ling.k8s.io created
customresourcedefinition.apiextensions.k8s.io/verticalpodautoscalercheckpoints.p
oc.autoscaling.k8s.io created
clusterrole.rbac.authorization.k8s.io/system:metrics-reader created
clusterrole.rbac.authorization.k8s.io/system:vpa-actor created
clusterrole.rbac.authorization.k8s.io/system:vpa-checkpoint-actor created
clusterrole.rbac.authorization.k8s.io/system:evictioner created
clusterrolebinding.rbac.authorization.k8s.io/system:metrics-reader created
clusterrolebinding.rbac.authorization.k8s.io/system:vpa-actor created
clusterrolebinding.rbac.authorization.k8s.io/system:vpa-checkpoint-actor created

clusterrole.rbac.authorization.k8s.io/system:vpa-target-reader created
clusterrolebinding.rbac.authorization.k8s.io/system:vpa-target-reader-binding cr
eated
clusterrolebinding.rbac.authorization.k8s.io/system:vpa-evictionter-binding crea
ted
serviceaccount/vpa-admission-controller created
clusterrole.rbac.authorization.k8s.io/system:vpa-admission-controller created
clusterrolebinding.rbac.authorization.k8s.io/system:vpa-admission-controller cre
ated
clusterrole.rbac.authorization.k8s.io/system:vpa-status-reader created
clusterrolebinding.rbac.authorization.k8s.io/system:vpa-status-reader-binding cr
eated
customresourcedefinition.apiextensions.k8s.io/verticalpodautoscalers.autoscaling
.k8s.io configured
customresourcedefinition.apiextensions.k8s.io/verticalpodautoscalercheckpoints.a
utoscaling.k8s.io configured
```

4. VPA Admission Controller does not get created.

```

C:\EKS>kubectl get pods -n kube-system
NAME                                        READY   STATUS              RESTARTS
   AGE
aws-node-6nkfq                              1/1     Running             0
   179m
aws-node-6wtjz                              1/1     Running             0
   177m
aws-node-wnqnc                              1/1     Running             0
   175m
coredns-56678dcf76-77xhp                    1/1     Running             0
   176m
coredns-56678dcf76-f44cw                    1/1     Running             0
   3h
kube-proxy-87f6m                            1/1     Running             0
   179m
kube-proxy-qt8f7                            1/1     Running             0
   175m
kube-proxy-z5w84                            1/1     Running             0
   177m
metrics-server-7fcf9cc98b-lczwp             1/1     Running             0
   134m
vpa-admission-controller-69bf4dd698-hhd9b   0/1     ContainerCreating   0
   39s
vpa-recommender-6cf9fd5c45-9hwlx            1/1     Running             0
   44s
vpa-updater-7d9db6565c-xgfzj                1/1     Running             0
   43s

```

**Comment by bskiba** [comment] 2020-02-10 09:20
Can you paste the result of 
`kubectl describe pod -n kube-system vpa-admission-controller-69bf4dd698-hhd9b`

**Comment by dvohra** [comment] 2020-02-10 22:42
Is any other configuration needed than discussed at https://docs.aws.amazon.com/eks/latest/userguide/vertical-pod-autoscaler.html?

 Requested output is as follows.

```
C:\EKS>kubectl describe pod -n kube-system vpa-admission-controller-69bf4dd698-q
dj76
Name:           vpa-admission-controller-69bf4dd698-qdj76
Namespace:      kube-system
Priority:       0
Node:           ip-192-168-88-36.ec2.internal/192.168.88.36
Start Time:     Mon, 10 Feb 2020 14:37:31 -0800
Labels:         app=vpa-admission-controller
                pod-template-hash=69bf4dd698
Annotations:    kubernetes.io/psp: eks.privileged
Status:         Pending
IP:
IPs:            <none>
Controlled By:  ReplicaSet/vpa-admission-controller-69bf4dd698
Containers:
  admission-controller:
    Container ID:
    Image:          k8s.gcr.io/vpa-admission-controller:0.6.3
    Image ID:
    Port:           8000/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     200m
      memory:  500Mi
    Requests:
      cpu:     50m
      memory:  200Mi
    Environment:
      NAMESPACE:  kube-system (v1:metadata.namespace)
    Mounts:
      /etc/tls-certs from tls-certs (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from vpa-admission-controlle
r-token-ng8tz (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  tls-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  vpa-tls-certs
    Optional:    false
  vpa-admission-controller-token-ng8tz:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  vpa-admission-controller-token-ng8tz
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason       Age                  From
     Message
  ----     ------       ----                 ----
     -------
  Normal   Scheduled    2m18s                default-scheduler
     Successfully assigned kube-system/vpa-admission-controller-69bf4dd698-qdj76
 to ip-192-168-88-36.ec2.internal
  Warning  FailedMount  74s (x8 over 2m18s)  kubelet, ip-192-168-88-36.ec2.inter
nal  MountVolume.SetUp failed for volume "tls-certs" : secrets "vpa-tls-certs" n
ot found
```

C:\EKS>

**Comment by bskiba** [comment] 2020-02-11 09:32
> Is any other configuration needed than discussed at https://docs.aws.amazon.com/eks/latest/userguide/vertical-pod-autoscaler.html?
This is a question to the author of that documentation, it was not created by SIG Autoscaling

To the original problem. From the logs:
> kubelet, ip-192-168-88-36.ec2.internal  MountVolume.SetUp failed for volume "tls-certs" : secrets "vpa-tls-certs" not found

The vpa-tls-certs secret is created by [gencerts.sh](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/admission-controller/gencerts.sh) script. You created the VPA by 
`kubectl apply -f  autoscaler\vertical-pod-autoscaler\deploy\`

This does not generate the needed certs. Both the docs you mention and documentation in this repo make the installation step
`./hack/vpa-up.sh`
You need to either use this script to deploy VPA or generate the certs yourself (for exmaple by running gencerts.sh)

**Comment by bskiba** [comment] 2020-02-11 09:36
/close
I'm closing the issue, please reopen if the instruction from previous comment doesn't help

**Closed by bskiba** 2020-02-11 09:36 UTC
Labels: vertical-pod-autoscaler

**Comment by dvohra** [comment] 2020-02-11 17:34
While AWS EKS is very much supported on Windows, the .sh scripts that generate the certs for the VPA don't seem to be favorable to Windows. Installed Git Bash to run the .sh scripts, but still getting :

```
dvohra@dvohra-PC MINGW64 /c/EKS/autoscaler/vertical-pod-autoscaler/hack
$ sh vpa-up.sh
Generating certs for the VPA Admission Controller in /tmp/vpa-certs.
Generating RSA private key, 2048 bit long modulus (2 primes)
..............................................................+++++
..........................................................+++++
e is 65537 (0x010001)
name is expected to be in the format /type0=value0/type1=value1/type2=... where characters may be escaped by \. This name is not in that format: 'C:/Program Files/Git/CN=vpa_webhook_ca'
problems making Certificate Request
sh: __git_ps1: command not found
```

**Comment by bskiba** [comment] 2020-02-12 09:27
This is a very standard script for generating webhook certificates for Kubernetes: https://github.com/kubernetes/apiserver/blob/master/pkg/util/webhook/gencerts.sh

The problem seems to be in this line: https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/admission-controller/gencerts.sh#L40

Can you try to change it to:
openssl req -x509 -new -nodes -key ${TMP_DIR}/caKey.pem -days 100000 -out ${TMP_DIR}/caCert.pem -subj "/CN=vpa_webhook_ca"

**Comment by AdamSzendrei** [comment] 2020-08-18 09:17
when I start the script vpa-ip.sh I get the following error:
`Generating certs for the VPA Admission Controller in /tmp/vpa-certs.
Generating RSA private key, 2048 bit long modulus
............+++
.......+++
e is 65537 (0x10001)
unknown option -addext
req [options] <infile >outfile`

**Comment by bskiba** [comment] 2020-08-18 09:19
@AdamSzendrei please take a look at 
https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler#install-command

**Comment by AdamSzendrei** [comment] 2020-08-18 09:35
my openssl is up-to-date and I still have the same issue.

**Comment by ZhaoNeil** [comment] 2021-06-02 17:20
> > Is any other configuration needed than discussed at https://docs.aws.amazon.com/eks/latest/userguide/vertical-pod-autoscaler.html?
> 
> This is a question to the author of that documentation, it was not created by SIG Autoscaling
> 
> To the original problem. From the logs:
> 
> > kubelet, ip-192-168-88-36.ec2.internal  MountVolume.SetUp failed for volume "tls-certs" : secrets "vpa-tls-certs" not found
> 
> The vpa-tls-certs secret is created by [gencerts.sh](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/admission-controller/gencerts.sh) script. You created the VPA by
> `kubectl apply -f autoscaler\vertical-pod-autoscaler\deploy\`
> 
> This does not generate the needed certs. Both the docs you mention and documentation in this repo make the installation step
> `./hack/vpa-up.sh`
> You need to either use this script to deploy VPA or generate the certs yourself (for example by running gencerts.sh)

 Hi, when I tried `./hack/vpa-up.sh`, it shows:
```
customresourcedefinition.apiextensions.k8s.io/verticalpodautoscalercheckpoints.autoscaling.k8s.io created
customresourcedefinition.apiextensions.k8s.io/verticalpodautoscalers.autoscaling.k8s.io created
clusterrole.rbac.authorization.k8s.io/system:metrics-reader created
clusterrole.rbac.authorization.k8s.io/system:vpa-actor created
clusterrole.rbac.authorization.k8s.io/system:vpa-checkpoint-actor created
clusterrole.rbac.authorization.k8s.io/system:evictioner created
clusterrolebinding.rbac.authorization.k8s.io/system:metrics-reader created
clusterrolebinding.rbac.authorization.k8s.io/system:vpa-actor created
clusterrolebinding.rbac.authorization.k8s.io/system:vpa-checkpoint-actor created
clusterrole.rbac.authorization.k8s.io/system:vpa-target-reader created
clusterrolebinding.rbac.authorization.k8s.io/system:vpa-target-reader-binding created
clusterrolebinding.rbac.authorization.k8s.io/system:vpa-evictionter-binding created
serviceaccount/vpa-admission-controller created
clusterrole.rbac.authorization.k8s.io/system:vpa-admission-controller created
clusterrolebinding.rbac.authorization.k8s.io/system:vpa-admission-controller created
clusterrole.rbac.authorization.k8s.io/system:vpa-status-reader created
clusterrolebinding.rbac.authorization.k8s.io/system:vpa-status-reader-binding created
serviceaccount/vpa-updater created
deployment.apps/vpa-updater created
serviceaccount/vpa-recommender created
deployment.apps/vpa-recommender created
Generating certs for the VPA Admission Controller in /tmp/vpa-certs.
./../hack/../pkg/admission-controller/gencerts.sh: line 29: /tmp/vpa-certs/server.conf: Permission denied
deployment.apps/vpa-admission-controller created
service/vpa-webhook created
```
and if I run `sudo ./gencerts.sh`, it shows:
```
Generating certs for the VPA Admission Controller in /tmp/vpa-certs.
Generating RSA private key, 2048 bit long modulus (2 primes)
..........................................................+++++
..................................+++++
e is 65537 (0x010001)
Generating RSA private key, 2048 bit long modulus (2 primes)
.........+++++
...............................+++++
e is 65537 (0x010001)
Signature ok
subject=CN = vpa-webhook.kube-system.svc
Getting CA Private Key
Uploading certs to the cluster.
The connection to the server 132.229.44.151:8443 was refused - did you specify the right host or port?
```
Would you be able to give me any suggestions?

**Comment by kennydgreat** [comment] 2022-10-31 15:55
> While AWS EKS is very much supported on Windows, the .sh scripts that generate the certs for the VPA don't seem to be favorable to Windows. Installed Git Bash to run the .sh scripts, but still getting :
> 
> ```
> dvohra@dvohra-PC MINGW64 /c/EKS/autoscaler/vertical-pod-autoscaler/hack
> $ sh vpa-up.sh
> Generating certs for the VPA Admission Controller in /tmp/vpa-certs.
> Generating RSA private key, 2048 bit long modulus (2 primes)
> ..............................................................+++++
> ..........................................................+++++
> e is 65537 (0x010001)
> name is expected to be in the format /type0=value0/type1=value1/type2=... where characters may be escaped by \. This name is not in that format: 'C:/Program Files/Git/CN=vpa_webhook_ca'
> problems making Certificate Request
> sh: __git_ps1: command not found
> ```

For anyone who comes across this same error this is caused by POSIX-to-Windows path conversion on GitBash. It converts command-line options starting with a slash to paths so on [gencerts.sh](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/admission-controller/gencerts.sh) line 44 the openssl -subj option `"/CN=${CN_BASE}_ca"` becomes  `"C:/Program Files/Git/CN=vpa_webhook_ca"` which is the wrong format. To resolve this simply escape the slash by adding a '/' in front of all command-line options values that start with slash. So `"/CN=${CN_BASE}_ca"` should be `"//CN=${CN_BASE}_ca"`.
