### ISSUE TITLE
Allow Cluster API node groups to scale to and from zero

### ISSUE THREAD

**Issue by mkjpryor** [kubernetes/autoscaler#4758] opened 2022-03-22 13:01 UTC
**Which component are you using?**:

cluster-autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

I have a Cluster API cluster with some general purpose nodes and some specialist, expensive nodes that is used for batch-type workloads. I would like to be able to scale the specialist nodes down to zero unless a workload needs them.

**Describe the solution you'd like.**:

For the cluster autoscaler to be able to scale Cluster API machine deployments to and from zero nodes.

**Describe any alternative solutions you've considered.**:

None - the cluster autoscaler works perfectly for everything except this.

**Additional context.**:

N/A

**Comment by elmiko** [comment] 2022-04-29 18:16
this appears to be a duplicate of https://github.com/kubernetes/autoscaler/issues/3150

/close

**Closed** 2022-04-29 18:17 UTC
Labels: cluster-autoscaler, kind/feature
