### ISSUE TITLE
Nodes tainted with ToBeDeletedByClusterAutoscaler remain in the cluster blocking cluster-autoscaler normal operations

### ISSUE THREAD

**Issue by mimmus** [kubernetes/autoscaler#5657] opened 2023-04-05 09:14 UTC
**Which component are you using?**:
cluster-autoscaler

**What version of the component are you using?**:
Image tag: cluster-autoscaler:v1.23.0

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.8", GitCommit:"7061dbbf75f9f82e8ab21f9be7e8ffcaae8e0d44", GitTreeState:"clean", BuildDate:"2022-03-16T14:10:06Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.8", GitCommit:"7061dbbf75f9f82e8ab21f9be7e8ffcaae8e0d44", GitTreeState:"clean", BuildDate:"2022-03-16T14:04:34Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:
AWS

**What did you expect to happen?**:
Nodes tainted for deletion should be deleted at some point

**What happened instead?**:
Nodes tainted for deletion (ToBeDeletedByClusterAutoscaler) remain in the cluster, blocking further scaleUp/scaleDown and causing disruption to normal operation (i.i. new pods remains in Pending state because new nodes cannot be added by CA).

**How to reproduce it (as minimally and precisely as possible)**:
I don't know.

**Anything else we need to know?**:
Args:
<pre>
          args:
            - '--cloud-provider=clusterapi'
            - '-v5'
            - '--balance-similar-node-groups'
            - '--balancing-ignore-label="topology.ebs.csi.aws.com/zone"'
            - '--scale-down-utilization-threshold=0.65'
            - '--skip-nodes-with-system-pods=false'
            - '--skip-nodes-with-local-storage=false'
</pre>

cluster-autoscaler is part of a commercial product, I have also opened a case with vendor but currently navigates in the dark.
I'm aware of:
https://github.com/kubernetes/autoscaler/issues/4456
https://github.com/kubernetes/autoscaler/issues/5048
I tried also the simplest workaround (add the `cluster-autoscaler.kubernetes.io/safe-to-evict: 'false'` annotation to cluster-autoscaler) but still getting nodes not deleted.

**Comment by vadasambar** [comment] 2023-04-13 04:29
`cluster-autoscaler.kubernetes.io/safe-to-evict: 'false'` has the opposite effect. It prevents the node from getting removed. 
![image](https://user-images.githubusercontent.com/34534103/231653697-487afff0-c591-4992-8de8-b097752c303f.png)
https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node

**Comment by vadasambar** [comment] 2023-04-13 04:38
I think CA (cluster-autoscaler) pod tried deleting the node on which it was running. In this case, it adds the `ToBeDeletedByClusterAutoscaler` and kicks itself out from the node before deleting it. 

I see 2 possibilities here:
1. The node with `ToBeDeletedByClusterAutoscaler` was not in a good state. New CA pod removes taints from all the nodes at initilization except there is a bug in 1.23 which has been fixed in the later versions where taints from only ready nodes is removed. https://github.com/kubernetes/autoscaler/blob/5af3685e86ab8ac5fdb848699e948cbd6d1c3d43/cluster-autoscaler/core/static_autoscaler.go#L182-L193
2. Scale down is in a cool down because of some reason. Check for a log like https://github.com/kubernetes/autoscaler/blob/5af3685e86ab8ac5fdb848699e948cbd6d1c3d43/cluster-autoscaler/core/static_autoscaler.go#L519-L524
If you see `scaleDownInCooldown=true`, scale down won't happen until the cool down is lifted. 

I suspect 2 might be the case here. 

If 2 doesn't turn out to be the case, I think it'd be hard to say what the problem is without looking at the logs.

**Comment by mimmus** [comment] 2023-04-13 07:59
> `cluster-autoscaler.kubernetes.io/safe-to-evict: 'false'` has the opposite effect. It prevents the node from getting removed.
That is exactly the effect I need: prevent the node where CA is running to be deleted. Or not?

**Comment by mimmus** [comment] 2023-04-14 19:40
UPDATE
If I restart cluster-autoscaler pod, it cleans all taints.

**Comment by comeonyo** [comment] 2023-04-16 14:16
@mimmus 
By default, the cluster autoscaler sets the node scale-in cooldown time to 10 minutes.

**Comment by mimmus** [comment] 2023-04-16 16:39
@comeonyo What exactly "scaleDownInCooldown" means is not really clear to me :( 
Could you elaborate? 

Thanks again

**Comment by vadasambar** [comment] 2023-04-17 04:55
> That is exactly the effect I need: prevent the node where CA is running to be deleted. Or not?

I see. I thought it was for all the nodes. :+1: 

> I don't know exactly what you mean by "not in good state"

Sorry, should have been clearer here. `not in a good state` here means the node is in `NotReady` state.

> I'm not able to find any scaleDownInCooldown=true in the logs.

I see you have set `-v5` which means the `scaleDownInCooldown` log should get printed irrespective of whether we are seeing the problem or not.

> I can collect and post logs somewhere, if you need.

If you are concerned about posting logs here, feel free to reach out to me on slack. 

P.S.: we recently merged https://github.com/kubernetes/autoscaler/pull/5632 which fixes #4456 for AWS. You can try it out and see if it fixes the issue for you.

> What exactly "scaleDownInCooldown" means is not really clear to me :(

It means scale down is disabled temporarily. This can happen for multiple reasons e.g., unless you specify `--scale-down-delay-after-add` with a different value, scale down is blocked temporarily for [10 minutes](https://github.com/kubernetes/autoscaler/blob/b1b7f3990893947692a978f9b36145f5e6fe0c59/cluster-autoscaler/main.go#L104) after scale up.

**Comment by mimmus** [comment] 2023-04-17 13:55
We'll post logs as soon the issue will happen again, usually every night.


> P.S.: we recently merged 5632 which fixes 4456 for AWS. You can try it out and see if it fixes the issue for you.

As far as I understand, I can use Cluster Autoscaler with the Kubernetes control plane version for which it was meant 
(I have K8s 1.22.8, CA is 1.23 but it is provided by vendor and thus I suppose it is correct).
In fact, I tried with CA 1.26 and it was a disaster.

Thanks again

**Comment by vadasambar** [comment] 2023-04-17 14:25
> As far as I understand, I can use Cluster Autoscaler with the Kubernetes control plane version for which it was meant

Sorry, you are right. You would have to create a new cluster with the latest control plane version to try it out (I don't think all cloud providers are supporting the latest 1.27 version at the time of writing this comment). 

We can look into patching it back to 1.26. 

>  (I have K8s 1.22.8, CA is 1.23 but it is provided by vendor and thus I suppose it is correct).

Not sure why that is the case. It is recommended to use the same major version for CA as the control plane.

**Comment by mimmus** [comment] 2023-04-21 09:34
Our vendor's support thinks that what may be happening is that the Kube-scheduler and autoscaler are in disagreement. 
There are many pods the autoscaler thinks can be scheduled, but the scheduler has them pending.
cluster-autoscaler believes that the upcoming node will be available but this realistically references back to one of mytainted nodes, thus the blocked state. This is the issue outlined in:
[https://github.com/kubernetes/autoscaler/issues/4456#issuecomment-1097333210
](url)

**Comment by vadasambar** [comment] 2023-04-24 04:24
> Our vendor's support thinks that what may be happening is that the Kube-scheduler and autoscaler are in disagreement.

If your vendor is using a scheduler 
- with non-default plugins/extenders
- with default plugins but non-default scheduler configuration

CA would be in disagreement with the scheduler because CA makes scale up decisions with the assumption that default scheduler with default scheduler configuration will be used.  

If your vendor is in-fact using a non-default scheduler or a non-default configuration, your vendor needs to make changes in CA to make it in-line with the cluster's scheduler, re-compile it and use the customized CA image.

**Comment by mimmus** [comment] 2023-05-22 07:51
It seems solved after upgrading clusters to kubernetes 1.23.12/cluster-autoscaler 1.23.1.

**Closed** 2024-03-21 00:10 UTC
Labels: area/cluster-autoscaler, kind/bug, lifecycle/rotten
