### ISSUE TITLE
VPA recommender prometheus history provider - cannot get timeseries for cpu: invalid response status: success or type: vector

### ISSUE THREAD

**Issue by edwardj9** [kubernetes/autoscaler#2508] opened 2019-11-04 04:29 UTC
Prometheus history provider isn't working on VPA 0.6.0+ because the prometheus client expects a matrix for the cpu data but it's a vector as the cpu query now uses rate() as introduced in #1824.

`E1104 04:23:55.334996       1 cluster_feeder.go:213] Cannot get cluster history: cannot get usage history: cannot get timeseries for cpu: invalid response status: success or type: vector
`

**Comment by bskiba** [comment] 2019-11-04 10:50
Thanks for reporting!
Should we revert the mentioned PR or do you have an idea for a fix?

**Comment by adityabhatia02** [comment] 2019-11-11 11:52
I am interested in contributing a fix for this; just not sure what the best way to fix it would be

**Comment by milesbxf** [comment] 2019-11-18 16:55
👋 we're having the same problem. The issue is actually that we're sending a query which only returns a set of timeseries with a single sample each, which for `/api/v1/query` defaults to the current timestamp). This is a "Vector" in Prometheus terminology. On the other hand, the history provider implementation expects a set of samples over time (a Matrix).

The simple fix here is to use the `/api/v1/query_range` endpoint instead, which lets us specify a start and end time to evaluate a query over. I'll have a go at raising a PR for this this week.

**Comment by milesbxf** [comment] 2019-11-19 14:31
@bskiba : https://github.com/kubernetes/autoscaler/pull/2544

**Comment by leoskyrocker** [comment] 2020-03-02 05:19
Does anyone know what the impact of this issue is? It seems that recommendation is still generated regardless of this error. However, it is unclear how, is it based on Prometheus or checkpoints when this error happens?

**Comment by yashbhutwala** [comment] 2020-04-15 01:29
ping, can we please get one of the MR's reviewed/merged? 😃

**Comment by bskiba** [comment] 2020-04-15 07:43
Yeah, I have some time set aside today to take a look, sorry for the delay.

**Comment by bskiba** [comment] 2020-05-08 09:24
/fixed
by #3009, thanks @povilasv

**Closed** 2020-05-08 09:24 UTC
Labels: kind/bug, vertical-pod-autoscaler
