### ISSUE TITLE
CA-1.0.3 AWS - unable to scale up from 0

### ISSUE THREAD

**Issue by bob-shih** [kubernetes/autoscaler#951] opened 2018-06-11 13:53 UTC
Issue summary:
Although CA could scale down nodes to 0 and can scale up from 1 node and above, however, it always failed to scale up from 0.
(Note: the node is tainted and deployment is via "nodeSelector".)

Versions used:
CA:         1.0.3
Kube:       1.8.5
Cloud:      AWS
EC2 type:   m5.4xlarge

AWS ASG tags applied:
k8s.io/cluster-autoscaler/node-template/label/kubernetes.io/role worker-general
k8s.io/cluster-autoscaler/node-template/taint/dedicated worker-general:NoSchedule

Below are two scenarios that describe the issue.  They are reproducible.

Scenario 1:
===========
1. ASG (0,0,0,6) (running/desired/min/max)
2. CA is running
3. "helm install" my chart "bobchart" with values.yaml:
nodeSelector:
  kubernetes.io/role: "worker-general"
tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "worker-general"
    effect: "NoSchedule"
4. CA "panic" and in CrashLoopBackOff state
....
I0611 12:39:33.613810       1 scale_up.go:54] Pod default/bob-test-bobchart-574ddc49cf-xfwl7 is unschedulable
W0611 12:39:33.820311       1 aws_manager.go:225] Found multiple availability zones, using eu-west-1b
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1451bcd]

goroutine 83 [running]:
k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws.(*AwsManager).buildNodeFromTemplate(0xc4214825a0, 0xc4206e8960, 0xc4213fbcc0, 0xc4213fbcc0, 0x0, 0x0)
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws/aws_manager.go:252 +0x48d
k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws.(*Asg).TemplateNodeInfo(0xc4206e8960, 0xc4215cf0e0, 0x7ffcef946ee6, 0x24)
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go:355 +0x78
k8s.io/autoscaler/cluster-autoscaler/core.GetNodeInfosForGroups(0xc421444400, 0x5, 0x8, 0x50bc120, 0xc4206e8660, 0x50c64e0, 0xc4208b20d0, 0xc4210fc2e0, 0x4, 0x4, ...)
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/utils.go:211 +0x65a
k8s.io/autoscaler/cluster-autoscaler/core.ScaleUp(0xc420dc2680, 0xc42000fd40, 0x1, 0x1, 0xc421444400, 0x5, 0x8, 0xc4210fc2e0, 0x4, 0x4, ...)
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/scale_up.go:57 +0x28e
k8s.io/autoscaler/cluster-autoscaler/core.(*StaticAutoscaler).RunOnce(0xc42149ea80, 0xed2b06485, 0xe13dc3040, 0x518f0a0, 0x0, 0x0)
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/static_autoscaler.go:253 +0x13ea
main.run(0xc42071e820)
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/main.go:262 +0x46f
main.main.func2(0xc420a7bda0)
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/main.go:344 +0x2a
created by k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run
    /gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:145 +0x97
.....
5. delete my chart, CA is running again 

Scenario 2:
===========
1. ASG (1,1,0,6) (running/desired/min/max)          <--- changed "desired" to 1, so "1" instance started up running
2. CA is running
3. "helm install" my chart "bobchart" with values.yaml:
nodeSelector:
  kubernetes.io/role: "worker-general"
tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "worker-general"
    effect: "NoSchedule"
4. CA continuous to run and pod is created on correct node - ok
5. Deployed additional 16 charts so that CA will need to scale up. - ok
6. CA successfully scaled up to two nodes - ok
7. Delete all the additional 16 pods, CA scaled down the "older" node - ok
8. ASG (1,1,0,6) - ok
9. Delete the first (and the only remaining) pod, CA scale down all node - ok
10. ASG (0,0,0,6) - ok
11. Tried to deploy 1 chart, CA failed to scale up node from "0" and "panic" - failed

In both scenarios, CA failed to scale up from 0.  Attached please find the output for "pod" and "node" from "kubectl get".

To be able to scale up from 0 is crucial for us as we run certain job on demand only and does not require a node that runs all the time.

Thanks in advance.

Bob
[bob-test-bobchart_pod.txt](https://github.com/kubernetes/autoscaler/files/2090211/bob-test-bobchart_pod.txt)
[worker-general_node.txt](https://github.com/kubernetes/autoscaler/files/2090212/worker-general_node.txt)

**Comment by aleksandra-malinowska** [comment] 2018-06-11 14:48
Looks like a duplicate of #821. You can try using a newer version of Cluster Autoscaler. The panic is _possibly_ caused by old AWS code being unable to handle newer instance types.

**Closed by aleksandra-malinowska** 2018-06-11 14:48 UTC

**Comment by bob-shih** [comment] 2018-06-11 15:43
Hi Aleksandra,
My issue is my Kube version is 1.8.5 and according to "https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler", I will need to use CA version 1.0.X. The latest version that I could pull is 1.0.5 that still does not work and CA still "panic" when trying to upscale from 0.  (Btw, my EC2 type is m5.4xlarge that is not such a latest addition.)

Thanks.

Bob

**Comment by aleksandra-malinowska** [comment] 2018-06-11 15:55
The guidelines are based on the configurations that have been tested by Cluster Autoscaler maintainers on GCP. To the best of my knowledge, there hasn't been any such tests on AWS, but there are user reports of configurations that work. See discussion in the other issue - it seems the problem there was with a similar instance type.

**Comment by bob-shih** [comment] 2018-06-11 16:08
Hi Aleksandra,
Thanks for the pointing out that the guideline is not applicable to all.  CA v1.2.2 seems to work with my Kube 1.8.5 in AWS for EC2 instance type m5.4xlarge.  It has successfully upscaled from 0.

**Comment by aleksandra-malinowska** [comment] 2018-06-11 16:57
Glad to know it works for you now. Also, contributions are welcome, and if you'd like to help get rid of those panics, just send a PR :)
