### ISSUE TITLE
Installing Git Dependencies Fails on cluster-autoscaler-1.24.0

### ISSUE THREAD

**Issue by jonathanmeier5** [kubernetes/autoscaler#5180] opened 2022-09-08 14:51 UTC
Hey all, ran into an issue when attempting to install the dependencies from tag `cluster-autoscaler-1.24.0`.

**Which component are you using?**:
cluster-autoscaler

**What did you run?**
```
export GOPROXY=direct
git clone git@github.com:kubernetes/autoscaler.git
cd autoscaler/cluster-autoscaler
git checkout f69e14b5de2e595b55f4ee4dc64952e00e7c7ee9
go get
verifying sigs.k8s.io/cloud-provider-azure@v1.23.2: checksum mismatch
	downloaded: h1:IkKwDPi8M8X5mWdn5AyAVTmqi1GNI1NoFQYmCYMDydo=
	go.sum:     h1:DQuKWZ168Ei8iterMX5Ri02DtcoKWbU1S2Jkqwk6aDw=
```

**What did you expect to happen?**:

I expected the dependencies to install.

**What happened instead?**:
The dependencies failed to install due to a bad hash.

**How to reproduce it (as minimally and precisely as possible)**:
```
export GOPROXY=direct
git clone git@github.com:kubernetes/autoscaler.git
cd autoscaler/cluster-autoscaler
git checkout f69e14b5de2e595b55f4ee4dc64952e00e7c7ee9
go get
verifying sigs.k8s.io/cloud-provider-azure@v1.23.2: checksum mismatch
	downloaded: h1:IkKwDPi8M8X5mWdn5AyAVTmqi1GNI1NoFQYmCYMDydo=
	go.sum:     h1:DQuKWZ168Ei8iterMX5Ri02DtcoKWbU1S2Jkqwk6aDw=
```

**Anything else we need to know?**:
Using golang 1.18.5 on macOS Monterey 12.4.

offending commit/line of code: https://github.com/kubernetes/autoscaler/blob/f69e14b5de2e595b55f4ee4dc64952e00e7c7ee9/cluster-autoscaler/go.sum#L1364

I filed [this](https://github.com/kubernetes-sigs/cloud-provider-azure/issues/2287) issue with the azure provider repo.

**Comment by Shubham82** [comment] 2022-09-29 05:51
Closing this issue, as the issue is resolved by this PR #5215
/close

**Closed by Shubham82** 2022-09-29 05:51 UTC
Labels: cluster-autoscaler, kind/bug
