### ISSUE TITLE
Cluster-autoscaler avoiding nodes because of daemonsets

### ISSUE THREAD

**Issue by iMartyn** [kubernetes/autoscaler#2181] opened 2019-07-10 09:36 UTC
We have a 5-node cluster that is running prometheus-node-exporter as a daemonset and cluster-autoscaler is failing to scale it down because the pods would not be schedulable elsewhere (no surprise, they're a daemonset!).

Relevant lines from the logs :
```
I0710 09:25:59.483559       1 utils.go:552] No pod using affinity / antiaffinity found in cluster, disabling affinity predicate for this loop
I0710 09:25:59.484103       1 scale_up.go:263] Pod monitoring/kube-prometheus-exporter-node-547zm is unschedulable
I0710 09:25:59.484117       1 scale_up.go:263] Pod monitoring/kube-prometheus-exporter-node-vd6j5 is unschedulable
I0710 09:25:59.484121       1 scale_up.go:263] Pod monitoring/mi-prom-operator-prometheus-node-exporter-xnc5c is unschedulable
I0710 09:25:59.484124       1 scale_up.go:263] Pod monitoring/mi-prom-operator-prometheus-node-exporter-svxqq is unschedulable
I0710 09:25:59.484128       1 scale_up.go:263] Pod monitoring/kube-prometheus-exporter-node-wcjnl is unschedulable
I0710 09:25:59.484170       1 utils.go:208] Pod kube-prometheus-exporter-node-547zm can't be scheduled on nodepool1, predicate failed: GeneralPredicates predicate mismatch, reason: node(s) didn't have free ports for the requested pod ports, node(s) didn't match node selector
I0710 09:25:59.484237       1 utils.go:208] Pod kube-prometheus-exporter-node-vd6j5 can't be scheduled on nodepool1, predicate failed: GeneralPredicates predicate mismatch, reason: node(s) didn't have free ports for the requested pod ports, node(s) didn't match node selector
I0710 09:25:59.484250       1 utils.go:208] Pod mi-prom-operator-prometheus-node-exporter-xnc5c can't be scheduled on nodepool1, predicate failed: GeneralPredicates predicate mismatch, reason: node(s) didn't have free ports for the requested pod ports, node(s) didn't match node selector
I0710 09:25:59.484318       1 utils.go:208] Pod mi-prom-operator-prometheus-node-exporter-svxqq can't be scheduled on nodepool1, predicate failed: GeneralPredicates predicate mismatch, reason: node(s) didn't have free ports for the requested pod ports, node(s) didn't match node selector
I0710 09:25:59.484436       1 utils.go:208] Pod kube-prometheus-exporter-node-wcjnl can't be scheduled on nodepool1, predicate failed: GeneralPredicates predicate mismatch, reason: node(s) didn't have free ports for the requested pod ports, node(s) didn't match node selector
I0710 09:25:59.484449       1 scale_up.go:411] No expansion options
I0710 09:25:59.484633       1 scale_down.go:371] Scale-down calculation: ignoring 5 nodes unremovable in the last 5m0s
I0710 09:25:59.484784       1 scale_down.go:641] No candidates for scale down
```
Provider : AKS
K8s version : 1.12.8
ca version : 1.12.5
ca args :  --v=3 --logtostderr=true --cloud-provider=azure --skip-nodes-with-local-storage=false --nodes=3:10:nodepool1

Single nodepool, no vmss, nothing particularly special.

**Comment by iMartyn** [comment] 2019-07-11 12:23
Further information, we had two daemonsets conflicting with each other (using the same port) and so the pods were stuck in Pending.  Whilst I understand that this is an unusual scenario and it's understandable that CAS would not cope, excluding daemonset-created pods I think would be sensible in all cases.

**Comment by seanmalloy** [comment] 2019-07-12 02:09
In CA version 1.13 there is a command line option to ignore DaemonSets.

**Comment by MaciekPytel** [comment] 2019-07-12 14:41
CA ignores daemonsets running on node, but this seems to be caused by pending ones. There is no special treatment of pending daemonset pods. 
Any pending pod can block scale-down. Though it should not be true if the pod can't be helped by scale-up. @vivekbagade I think we already discussed this issue (with a different trigger) - a pod that is marked as NotTriggeredScaleUp should not block scale-down. Is this still on your radar?

**Comment by feiskyer** [comment] 2019-11-16 00:37
I'm closing the issue since there're no updates recently. Feel free reopen it if there're still issues.

/close

**Closed by feiskyer** 2019-11-16 00:37 UTC
Labels: lifecycle/rotten

**Comment by skraga** [comment] 2020-06-26 11:12
We're experiencing the same issue on our clusters. When daemonset pod is stuck in Pending state cluster is constantly growing up, the time when we caught this it was ~330 unneeded nodes.
Cloud provider: AWS
CA version: v1.16.5
