### ISSUE TITLE
Generic API based cluster autoscaler

### ISSUE THREAD

**Issue by zonca** [kubernetes/autoscaler#984] opened 2018-06-18 18:02 UTC
I think it would be great to have a cluster autoscaler that instead of interfacing directly with a cloud provider it would call a generic API endpoint with details about the request, for example to request a node to be removed or details about what kind of node to be created.
This would allow developers to write custom solutions that can work on their cloud platform with their backend of choice.

Hopefully this would not be too difficult to implement for someone familiar with the project starting from one of the existing supported providers.
Unfortunately I don't have the expertise to contribute this myself, but I would be happy to provide testing and feedback.

**Comment by aleksandra-malinowska** [comment] 2018-06-19 09:50
This is a duplicate of #191. Closing as there doesn't seem to be anyone working on this.

**Closed by aleksandra-malinowska** 2018-06-19 09:50 UTC
Labels: cluster-autoscaler

**Comment by zonca** [comment] 2018-06-19 10:02
Thanks! That is very useful!

**Comment by MaciekPytel** [comment] 2018-06-19 11:29
I think we should re-open either this or #191. It's true that no-one is working on it, but that doesn't mean such feature would not be useful.

**Comment by nikhilkhanna** [comment] 2018-07-08 01:50
Can we please reopen this issue? Such a feature would be great to allow for the long tail of other cloud providers to be interfaced with in a flexible manner.
