### ISSUE TITLE
Autoscaler not scale instance when only 1 pod is unschedulable

### ISSUE THREAD

**Issue by mashayev** [kubernetes/autoscaler#197] opened 2017-08-04 13:54 UTC
Hi All,

K8S version is: `v1.6.1`
Autoscaler version is: `v0.5.4` the same happened in `v0.5.1`
Provider: `AWS`

Not sure it's a bug or maybe configuration problem. Autoscaler not scaling another instance in case only 1 pod is unschedulable I saw it happens when 1 is unschedulable maybe the same goes for more.

I'm able to fix this only if I will create another pod and then the `scale_up.go` will `Estimated 1 nodes needed`

Logs:
```
I0804 13:23:44.597641       1 static_autoscaler.go:130] 1 unregistered nodes present
I0804 13:23:44.597684       1 static_autoscaler.go:197] Filtering out schedulables
I0804 13:23:44.597870       1 static_autoscaler.go:205] No schedulable pods
I0804 13:23:44.597893       1 scale_up.go:44] Pod <namespace>/<pod> is unschedulable
I0804 13:23:44.620660       1 scale_up.go:62] Upcoming 1 nodes
I0804 13:23:44.657738       1 scale_up.go:124] No need for any nodes in k8s-production-asg
I0804 13:23:44.657767       1 scale_up.go:132] No expansion options
I0804 13:23:44.657787       1 static_autoscaler.go:247] Scale down status: unneededOnly=true lastScaleUpTime=2017-08-04 13:17:36.225268892 +0000 UTC lastScaleDownFailedTrail=2017-08-03 18:27:44.967241708 +0000 UTC schedulablePodsPresent=false
```
After creating another pod:
```
0804 13:23:55.090329       1 scale_up.go:62] Upcoming 1 nodes
I0804 13:23:55.127798       1 scale_up.go:145] Best option to resize: k8s-production-asg
I0804 13:23:55.127826       1 scale_up.go:149] Estimated 1 nodes needed in k8s-production-asg
I0804 13:23:55.164701       1 scale_up.go:169] Scale-up: setting group k8s-production-asg size to 8
I0804 13:23:55.203865       1 aws_manager.go:124] Setting asg k8s-production-asg size to 8
```

YAML:
```
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: autoscaler-default-pool
  namespace: kube-system
  labels:
    app: autoscaler-default-pool
    asg-name: k8s-production-asg
spec:
  # replicas not specified on purpose, default 1
  selector:
    matchLabels:
      app: autoscaler-default-pool
  template:
    metadata:
      labels:
        app: autoscaler-default-pool
    spec:
      containers:
        - image: gcr.io/google_containers/cluster-autoscaler:v0.5.4
          name: cluster-autoscaler
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 300Mi
          command:
            - ./cluster-autoscaler
            - --kubernetes=https://elb.amazonaws.com:6443
            - --v=4
            - --stderrthreshold=info
            - --cloud-provider=aws
            - --skip-nodes-with-local-storage=true
            - --nodes=2:50:k8s-production-asg
          env:
            - name: AWS_REGION
              value: us-west-1
          volumeMounts:
            - name: ssl-certs
              mountPath: /etc/ssl/certs/ca-certificates.crt
              readOnly: true
          imagePullPolicy: Always
      volumes:
        - name: ssl-certs
          hostPath:
            path: /etc/pki/tls/certs/ca-bundle.crt
```

**Comment by MaciekPytel** [comment] 2017-08-04 14:13
Hi @mashayev, 
The critical line in the first log is 

`I0804 13:23:44.620660       1 scale_up.go:62] Upcoming 1 nodes`

That means that cluster-autoscaler believes there is one node that is already starting up. In that case it checks if all pending pods will fit on this node once it starts up. It only triggers scale-up if some pods won't fit on this upcoming node, so my guess is adding another pod makes cluster-autoscaler think one node is not enough and add another one.

Now, why does CA thinks there is an upcoming node? It compares ASG target size with how many nodes it sees in k8s and considers the difference to be nodes that are starting up now. If a node stays unregistered for 15 minutes CA should decide something's wrong with it and delete it.

So in your case my guess is either the original pending pod already caused a scale up, but the node haven't started yet (it takes up to 5 minutes to start VM, run kubelet, etc). Or there is some node in your ASG that failed to start up, but hasn't been deleted by CA yet.

Finally you can check if there is any ongoing scale up by checking status configmap with:
`kubectl get configmap cluster-autoscaler-status -n kube-system -o yaml`

**Comment by mashayev** [comment] 2017-08-04 14:38
@MaciekPytel Thanks for the clarification. 
The thing is it's not happening every time, I'm trying to reproduce this issue and the majority of the time the autoscaler is working fine. Some times it is not scaling and I'm able to see `Upcoming 1 nodes` for a long time.

Is it a  know issue? IS there any way to fix it? Maybe it's related to K8S v1.6.1?

**Comment by mashayev** [comment] 2017-08-04 14:50
@MaciekPytel I could reproduce this issue again, look like the CA failed to register the Node and it's still unregistered.. 

> If a node stays unregistered for 15 minutes CA should decide something's wrong with it and delete it.

Can I reduce the 15m for less ?

```
➜  ~ kubectl get configmap cluster-autoscaler-status -n kube-system -o yaml                   
apiVersion: v1
data:
  status: |+
    Cluster-autoscaler status at 2017-08-04 14:43:40.552637077 +0000 UTC:
    Cluster-wide:
      Health:      Healthy (ready=10 unready=0 notStarted=0 longNotStarted=0 registered=10)
                   LastProbeTime:      2017-08-04 14:43:39.709980994 +0000 UTC
                   LastTransitionTime: 2017-08-03 18:27:55.053846379 +0000 UTC
      ScaleUp:     InProgress (ready=10 registered=10)
                   LastProbeTime:      2017-08-04 14:43:39.709980994 +0000 UTC
                   LastTransitionTime: 2017-08-04 14:32:56.359845521 +0000 UTC
      ScaleDown:   NoCandidates (candidates=0)
                   LastProbeTime:      2017-08-04 14:43:40.254813288 +0000 UTC
                   LastTransitionTime: 2017-08-04 14:34:20.905639907 +0000 UTC

    NodeGroups:
      Name:        k8s-production-asg
      Health:      Healthy (ready=6 unready=0 notStarted=0 longNotStarted=0 registered=6 cloudProviderTarget=7 (minSize=2, maxSize=70))
                   LastProbeTime:      2017-08-04 14:43:39.709980994 +0000 UTC
                   LastTransitionTime: 2017-08-03 18:27:55.053846379 +0000 UTC
      ScaleUp:     InProgress (ready=6 cloudProviderTarget=7)
                   LastProbeTime:      2017-08-04 14:43:39.709980994 +0000 UTC
                   LastTransitionTime: 2017-08-04 14:32:56.359845521 +0000 UTC
      ScaleDown:   NoCandidates (candidates=0)
                   LastProbeTime:      2017-08-04 14:43:40.254813288 +0000 UTC
                   LastTransitionTime: 2017-08-04 14:34:20.905639907 +0000 UTC

kind: ConfigMap
metadata:
  annotations:
    cluster-autoscaler.kubernetes.io/last-updated: 2017-08-04 14:43:40.552637077 +0000
      UTC
  creationTimestamp: 2017-08-03T08:22:23Z
  name: cluster-autoscaler-status
  namespace: kube-system
  resourceVersion: "28796369"
  selfLink: /api/v1/namespaces/kube-system/configmaps/cluster-autoscaler-status
  uid: e08d1fb1-7824-11e7-a26e-025374a5bbd4
```

**Comment by MaciekPytel** [comment] 2017-08-04 15:05
You can change the 15 minute timeout by setting `--max-node-provision-time` and `--unregistered-node-removal-time` flags (I recommend setting both to the same value). That is, however, tackling the symptoms and not the root cause of the problem.

In k8s nodes are registered by kubelet running on them (ie. node registers itself). The only thing CA does is change the size of ASG (or MIG on GCP, or ScalingSet or Azure, ...). If the nodes fail to register I would recommend debugging why that happens. I would start by ssh-ing to the problematic machine and checking kubelet logs. I'm not an expert on this though.

**Comment by MaciekPytel** [comment] 2017-08-07 09:56
Based on discussion above it looks like cluster-autoscaler worked as expected and the problem was on the node side, so I'm closing this issue. Please re-open if required.

**Closed by MaciekPytel** 2017-08-07 09:56 UTC
